export const en = {
  common: {
    apply: "Apply",
    search: "Search",
    searchMenu: "Search menu...",
    noMenuResults: "No matching tabs",
    clearSearch: "Clear search",
    searchOrCreate: "Search or create",
    loading: "Loading...",
    loadMore: "Load more",
    noMoreData: "No more data",
    update: "Update",
    create: "Create",
    goBack: "Go Back",
    save: "Save",
    cancel: "Cancel",
    close: "Close",
    delete: "Delete",
    noOptionsAvailable: "No options available",
    noResultsFound: "No results found",
    noCharactersFoundMatchingYourSearch: "No characters found matching your search",
    select: "Select",
    uploading: "Uploading...",
    enabled: "Enabled",
    disabled: "Disabled",
    edit: "Edit",
    view: "View",
    or: "OR",
    retry: "Retry",
    characters: "characters",
    character: "character",
    successfullyDeleted: "Successfully deleted",
    thisActionCannotBeUndone: "This action cannot be undone.",
    areYouSureYouWantToDelete: "Are you sure you want to delete",
    maxActiveUsers: {
      title: "We're at capacity right now",
      description:
        "We're currently handling the maximum number of active users. Please wait a moment and try again access usually frees up shortly.",
      retry: "Retry",
      manualRetry: "You can retry in {seconds}s",
      autoRetry: "We'll automatically retry in {seconds}s",
    },
  },
  errors: {
    failedToCreateTooltip: "Failed to create tooltip",
    failedToUpdateTooltip: "Failed to update tooltip",
    maxRowsBehavioursInstruction: "You can only add up to 10 rows of behaviours instruction.",
    overviewMandatoryFieldsNotFilled:
      "Please fill all mandatory fields in the Overview step to proceed.",
    failedCompetencyCreation: "Failed to create competency",
    failedCompetencyUpdate: "Failed to rename competency",
    failedCompetencyDeletion: "Failed to delete competency",
    failedToDeleteBadges: "Failed to delete badges",
    failedToDeleteCharacter: "Failed to delete character(s)",
    failedToGoogleSignIn: "Failed to sign in with Google. Please try again.",
    failedCreateOrganization: "Failed to create organization",
    fileMustBeJPEGOrPNG: "File must be JPEG or PNG.",
    fileMustBeVideo: "File must be a video.",
    fileUploadFailed: "Failed to upload file. Please try again.",
    videoUploadFailed: "Failed to upload video. Please try again.",
    fileMetadataLoadFailed: "Failed to load video metadata",
    imageMustHave169AspectRatio: "Image must have a 16:9 aspect ratio.",
    imageMustHave1AspectRatio: "Please upload an image with the correct aspect ratio",
    fileDeleteFailed: "Failed to delete file. Please try again.",
    titleIsRequired: "Title should be filled to save as draft",
    failedSimulationChange: "Failed to save simulation changes!",
    failedPathwayChange: "Failed to save Tracks changes!",
    failedSaveDraft: "Failed to save draft. Please try again.",
    failedSimulationCreation: "Failed to create simulation. Please try again.",
    pathUpdateFailed: "Failed to update track access.",
    caseUpdateFailed: "Failed to update case access.",
    failedUpdateAccess: "Failed to update access.",
    failedUpdateBadgeAccess: "Failed to update badge access.",
    OrganizationNotFound: "Organization not found",
    minimumScoreError: "Minimum score must be a positive integer",
    failedToCreateEvent: "Failed to create event",
    failedToProceed: "Fill atleast title field to proceed to Event Configuration!",
    failedToSaveEvents: "Failed to save events. Please try again.",
    failedToDeleteEvent: "Failed to delete event. Please try again.",
    errorUpdatingEvent: "Error updating event",
    userIdNotFound: "User id not found",
    failedToRemoveUser: "Failed to remove user",
    failedToUploadImage: "Failed to upload image",
    failedToLoadImage: "Failed to load image",
    failedToLoadVoices: "Failed to load voices",
    failedToDeleteVoice: "Failed to delete voice",
    failedToSaveVoice: "Failed to save voice",
    failedToCancelReportGeneration: "Failed to cancel report generation",
    failedToRegenerate: "Failed to regenerate",
    failedToEnhance: "Failed to improve",
    failedToCreateFillerTag:
      "Could not create filler tag. It may already exist or the request failed.",
    linguisticStyleSamplesRequired:
      "Linguistic style samples are required. Please provide at least one sample for each selected language.",
    linguisticStyleSamplesMissingFor: (languages: string) =>
      `Linguistic style samples are required. Missing samples for: ${languages}.`,
    invalidStateInstructionIds: "State instructions include an invalid state id.",
  },
  accessDenied: {
    title: "This page is not accessible",
    message:
      "You don't have permission to access this page. Please contact your administrator if you believe this is an error.",
  },
  error: {
    apiRequestFailed: "API request failed",
    noRefreshDataReceived: "No refresh data received",
    tokenRefreshFailed: "Token refresh failed",
    userFetchFailed: "User fetch failed",
    permissionsFetchFailed: "Permissions fetch failed",
    authenticationFailed: "Authentication failed",
  },
  auth: {
    hey: "Hey",
    welcomeTo: "Welcome to",
    ally: "ally",
    email: "Email",
    password: "Password",
    login: "Login",
    signup: "Signup",
    forgotPassword: "Forgot Password",
    rememberMe: "Remember Me",
    generatingOTP: "Generating OTP...",
    termsAndConditions: "Terms & Conditions",
    privacyPolicy: "Privacy Policy",
    didNotReceiveTheCode: "Didn't receive the code?",
    signingIn: "Signing in...",
    logout: "Logout",
    enterEmailToContinue: "Enter your email address to continue",
    enterEmailPlaceholder: "Enter your email address",
    next: "Next",
    byTappingNext: "By proceeding, i agree to Ally's",
    andAcknowledge: "and acknowledge",
    verifyYourEmail: "Verify your email address",
    enterSecurityCode: "Enter the security code sent to",
    codeWillExpire: "This code will expire in",
    minutes: "minutes",
    needNewCode: "Need a new code?",
    resend: "Resend",
    verify: "Verify",
    helloAllyUrl: "helloally.ai",
    failedToGenerateOTP: "Failed to generate OTP. Please try again.",
    failedToVerifyOTP: "Failed to verify OTP. Please try again.",
    invalidEmailError: "Please enter a valid email address",
    profileSettings: "Profile settings",
    uploadImage: "Upload image",
    profileImage: "Profile image",
    verifyingMagicLink: "Verifying your magic link...",
    pleaseWait: "Please wait while we verify your link",
    magicLinkExpired: "Invalid or Expired Link",
    redirectingToLogin: "Redirecting to login page...",
    redirectingToDashboard: "Redirecting to dashboard...",
  },
  simulation: {
    untitledRoleplay: "Untitled Roleplay",
    autosaving: "Saving…",
    draftAutosaved: "Draft autosaved",
    autosaveFailed: "Couldn’t save — click Save to retry",
    versions: {
      title: "Versions",
      switchVersion: "Switch version",
      newVersion: "+ New version",
      loading: "Loading…",
      empty: "No versions yet. Create one to start iterating.",
      editing: "editing",
      openTooltip: "Open this version in the editor",
      branch: "Branch",
      rename: "Rename",
      delete: "Delete",
      create: "Create",
      save: "Save",
      cancel: "Cancel",
      namePlaceholder: "e.g. warmer opener",
      newBlankTitle: "New blank version",
      branchingFrom(label: string) {
        return `Branching from ${label}`;
      },
      deleteTitle: "Delete",
      deleteDescription: "This draft version will be removed. This can't be undone.",
      published: "Version published",
      readOnly: "read-only",
      readOnlyEdit: "This version is read-only. Branch it to make changes.",
      statusLabel: {
        DRAFT: "Draft",
        PUBLISHED: "Published",
        ARCHIVED: "Archived",
      } as Record<string, string>,
      created(label: string) {
        return `Created ${label}`;
      },
      renamed(label: string) {
        return `Renamed to ${label}`;
      },
      deleted(label: string) {
        return `Deleted ${label}`;
      },
      editingToast(label: string) {
        return `Editing ${label}`;
      },
      createError: "Couldn't create a new version",
      renameError: "Couldn't rename this version",
      deleteError: "Couldn't delete this version",
    },
    createCharacter: "Create character",
    editCharacter: "Edit character",
    characterCreatedSuccessfully: "Character created successfully",
    characterDeletedSuccessfully: "Character deleted successfully",
    failedToDeleteCharacter: "Failed to delete character",
    cases: "Cases",
    addSimulationToCase: "Add simulations to case",
    filterByGender: "Filter by gender",
    failedToCreateCharacter: "Failed to create character",
    failedToUpdateCharacter: "Failed to update character",
    characterUpdatedSuccessfully: "Character updated successfully!",
    characters: "Characters",
    createNewCharacter: "Create new character",
    duplicatePathwayDescription:
      "Are you sure you want to duplicate this Tracks? This will create a new Tracks with the same configurations.",
    duplicateSimulationDescription:
      "Are you sure you want to duplicate this simulation? This will create a new simulation with the same configurations",
    pathwayDuplicatedSuccessfully: "Tracks duplicated successfully",
    caseDuplicatedSuccessfully: "Case duplicated successfully",
    simulationDuplicatedSuccessfully: "Simulation duplicated successfully",
    failedDuplicatePathway: "Failed to duplicate Tracks",
    failedDuplicateCase: "Failed to duplicate case",
    failedDuplicateSimulation: "Failed to duplicate simulation",
    simulationDeletedSuccessfully: "Simulation deleted successfully",
    failedDeleteSimulation: "Failed to delete simulation",
    failedChangeSimulationStatus: "Failed to change simulation status",
    simulationStatusUpdatedSuccessfully: "Simulation status updated to ",
    failedChangePathwayStatus: "Failed to change Tracks status",
    pathwayStatusUpdatedSuccessfully: "Tracks status updated to ",
    failedChangeCaseStatus: "Failed to change case status",
    caseStatusUpdatedSuccessfully: "Case status updated to ",
    pathwayDeletedSuccessfully: "Tracks deleted successfully",
    caseDeletedSuccessfully: "Case deleted successfully",
    failedDeletePathway: "Failed to delete Tracks",
    failedDeleteCase: "Failed to delete case",
    deletePathway: "Delete Tracks",
    deletePathwayDescription:
      "I understand that deleting this simulation Tracks is permanent and that I will lose all access to users and simulation Tracks analytics.",
    pathway: "Tracks",
    paths: "Tracks",
    createPathway: "Create Tracks",
    videoMaxSizeLabel: "15MB",
    imageMaxSizeLabel: "2MB",
    file: "File",
    addEvent: "Add event",
    advancedEventsLatencyWarning: (count: number) =>
      `Heads up: ${count} advanced events are selected for this simulation. Selecting more than 10 can increase response latency during a session.`,
    bulkAddEvents: "Bulk add events",
    bulkAddEventsTitle: "Bulk add events",
    selectTags: "Select tags",
    noTagsAvailable: "No tags available",
    noTagsSelected: "No tags selected",
    filteredEventsCount: (count: number) => `${count} event${count !== 1 ? "s" : ""} will be added`,
    addSelectedEvents: "Add selected events",
    noEventsMatchTags: "No events match selected tags",
    bulkAddSuccess: (count: number) => `${count} event${count !== 1 ? "s" : ""} added successfully`,
    addSelectedEventsCount: (count: number) => `Add ${count} events`,
    unarchive: "Unarchive",
    atLeastOneLanguageMustHaveVoiceSelected: "At least one language must have a voice selected",
    unarchiveDescription:
      "Are you sure you want to unarchive this simulation? This will make it visible to active simulations.",
    voice: "Voice",
    selectVoice: "Select voice",
    removeVoiceDisableLanguage: "Remove voice (disable language)",
    simulationEvents: "Simulation Events",
    createNewEvent: "Create new event",
    createNewBadge: "Create New Badge",
    selectBadgeType: "Select the type of badge you want to create",
    selectEventType: "Select the type of event you want to create.",
    createEvent: "Create event",
    createBadge: "Create badge",
    editEvent: "Edit event",
    viewEvent: "View event",
    eventReadOnly:
      "This event is read-only. You can view its configuration but cannot make changes.",
    voices: "Voices",
    scenarioVoices: "Voices",
    searchVoices: "Search voices...",
    addVoice: "Add Voice",
    createVoice: "Create new voice",
    editVoice: "Edit Voice",
    voiceName: "Voice Name",
    name: "Name",
    icon: "Icon",
    category: "Category",
    orgVisibility: "Org. Visibility",
    enterVoiceName: "Enter voice name",
    provider: "Provider",
    enterProvider: "Enter provider",
    language: "Language",
    enterLanguage: "Enter language",
    model: "Model",
    enterModel: "Enter model",
    voiceCreatedSuccessfully: "Voice created successfully",
    voiceUpdatedSuccessfully: "Voice updated successfully",
    noVoicesFound: "No voices found",
    createFirstVoice: "Create your first scenario voice to get started",
    configurationCannotBeEmpty: "Configuration cannot be empty",
    configurationMustBeJsonObject:
      "Configuration must be a JSON object enclosed in curly braces {}",
    configurationMustNotBeArray: "Configuration must be a JSON object, not an array or primitive",
    invalidJsonSyntax: "Invalid JSON syntax",
    nameAndProviderRequired: "Name and provider are required",
    invalidConfigurationJson: "Invalid configuration JSON",
    nameProviderConfigRequired: "Name, provider, and valid configuration are required",
    deleteVoices: "Delete Voices",
    deleteVoicesConfirmation:
      "Are you sure you want to delete selected voices? This action cannot be undone.",
    languages: "Languages",
    scenarioLanguages: "Languages",
    searchLanguages: "Search languages...",
    addLanguage: "Add Language",
    createLanguage: "Create new language",
    editLanguage: "Edit Language",
    languageName: "Language Name",
    enterLanguageName: "Enter language name",
    languageCode: "Language Code",
    enterLanguageCode: "Enter language code",
    translationCode: "Translation Code",
    llmProviderConfig: "LLM Provider Config",
    sttProviderConfig: "STT Provider Config",
    enterTranslationCode: "Enter translation code",
    languageCreatedSuccessfully: "Language created successfully",
    languageUpdatedSuccessfully: "Language updated successfully",
    languageRequired: "Language name, code and translation code are required",
    fixConfigurationErrorsBeforeSaving: "Please fix configuration errors before saving",
    unsavedChangesWarning: "You have unsaved changes. Are you sure you want to close?",
    update: "Update",
    prompts: "System Skills",
    scenarioPrompts: "System Skills",
    searchPrompts: "Search prompts...",
    addPrompt: "Add Prompt",
    createPrompt: "Create new prompt",
    editPrompt: "Edit Prompt",
    promptName: "Prompt Name",
    enterPromptName: "Enter prompt name",
    promptCode: "Prompt Code",
    enterPromptCode: "Enter prompt code",
    promptDescription: "Description",
    enterPromptDescription: "Enter description",
    promptText: "Prompt",
    enterPrompt: "Enter prompt text",
    promptCreatedSuccessfully: "Prompt created successfully",
    promptUpdatedSuccessfully: "Prompt updated successfully",
    failedToUpdatePrompt: "Failed to update prompt",
    noPromptsFound: "No prompts found",
    createFirstPrompt: "Create your first prompt to get started",
    promptRequired: "Prompt name, description, prompt code and prompt text are required",
    useDashboardOverride: "Use dashboard version (when OFF, prompt is read from codebase folder)",
    useDashboardOverrideLabel: "Use dashboard version",
    availableVariables: "Available variables",
    usedBlocks: "Used Blocks",
    blocksHelpTitle: "What are blocks?",
    blocksHelpText:
      "Blocks are reusable prompt fragments referenced by this prompt. They are mainly used for optional or shared sections so the main prompt stays easier to read and maintain.",
    revertPromptSuccess: "Prompt restored to default successfully",
    revertPromptFailed: "Failed to restore prompt to default",
    restoreDefault: "Restore default",
    revertToDefaultConfirm:
      "Are you sure you want to restore this prompt to its codebase default? Your dashboard edits will be replaced.",
    deletePrompts: "Delete Prompts",
    deletePromptsConfirmation:
      "Are you sure you want to delete selected prompts? This action cannot be undone.",
    newSimulation: "New simulation",
    newTrack: "New track",
    createYourFirst: "Create your first",
    createYourFirstPathway: "Create your first Tracks",
    simulation: "Simulation",
    unpublish: "Unpublish",
    duplicate: "Duplicate",
    deleteEvent: "Delete event",
    unpublishDescription:
      "Are you sure you want to unpublish this simulation? This will be moved to draft state.",
    newSimulationDescription:
      "Build interactive scenarios for training, education, and practice with our intuitive creation tools.",
    newPathwayDescription: "Search and select simulations to include in this track.",
    createSimulation: "Create simulation",
    createNewSimulation: "Create new simulation",
    publish: "Publish",
    publishing: "Publishing...",
    basicInformation: "Basic Information",
    demographics: "Demographics & Background",
    narrativeContext: "Narrative Context",
    advancedSettings: "Advanced Settings",
    back: "Back",
    next: "Next",
    createdBy: "Created By",
    lastModified: "Last Modified",
    usage: "Usage",
    save: "Save",
    preview: "Preview",
    status: "Status",
    scenario: "Scenario",
    cancel: "Cancel",
    saveAndExit: "Save & Exit",
    discardChanges: "Discard Changes",
    starting: "Starting...",
    close: "Close",
    changes: "changes",
    unsaved: "Unsaved",
    discardDescription: "You have unsaved changes. What would you like to do?",
    archive: "Archive",
    archiveDescription:
      "Are you sure you want to archive this simulation? This will hide it from active simulations but you can restore it later.",
    delete: "Delete",
    deleteDescription: "Permanently delete this",
    deleteConfirmationText:
      "I understand that deleting this simulation is permanent and that I will lose all access to users and simulation analytics",
    deleteForever: "Delete forever",
    title: "Title",
    titlePlaceholder: "Enter title",
    coverImage: "Cover image",
    coverVideo: "Cover video",
    dragDrop: "Drag & drop or",
    choose: "choose",
    upload: "Upload",
    uploadFromImageLibrary: "browse image library.",
    generateWithAi: "Generate with AI",
    generatingImage: "Generating image...",
    imageGeneratedSuccessfully: "Image generated",
    imageGenerationFailed: "Failed to generate image",
    pngUploadGuidelinesOld: "a JPEG or PNG file with a",
    pngUploadGuidelines: "a JPEG or PNG file with a 16:9 aspect ratio under 2MB, or ",
    mp4UploadGuidelines: "a MP4 or MOV file with a",
    videoUploadGuidelines:
      "resolution of 16:9 aspect ratio,under 15MB, and a duration of up to 15 seconds.",
    resolutionOld: "resolution of 1920x1080 and under 2MB.",
    description: "Description",
    descriptionPlaceholder: "Enter description",
    tags: "Tags",
    learningGoal: "Learning Goal",
    agentGoal: "Agent Goal",
    currentThoughts: "Current Thoughts",
    learningGoalPlaceholder: "What is the primary learning goal?",
    agentGoalPlaceholder: "Describe the agent’s goal for this session.",
    keyLifeEvents: "Key life events",
    keyLifeEventsPlaceholder: "Describe the key life events",
    familyBackground: "Family background and relation",
    familyBackgroundPlaceholder: "Describe family background and relation",
    simulationstudio: "Simulation Studio",
    rolePlays: "Roleplays",
    editSimulation: "Edit Simulation",
    viewSimulation: "View Simulation",
    viewDetails: "View Details",
    partnerOrg: "Partner Org",
    readOnlyViewNote: "Read-only view — this simulation stays published.",
    publishTooltipMessage: "Publish becomes available after required details are filled and saved.",
    previewTooltipMessage: "Preview becomes available after required details are filled and saved.",
    generateReportTooltipMessage:
      "Complete all required fields and save your changes to generate a report.",
    generateReportTooltipMessageUnsavedChanges: "Save your changes to generate a report.",
    simulationPreview: "Simulation Preview",
    events: "Events",
    apply: "Apply",
    noResultFound: "No results found",
    adjustFilter: "Adjust your filters and try again.",
    edit: "Edit",
    editDescription:
      "Are you sure you want to edit this simulation? This will be moved to draft state.",
    startSession: "Start Session",
    autoTermination: "Auto termination",
    triggerEvent: "Trigger event",
    triggerMessage: "Termination dialogue",
    terminationMessagePlaceholder:
      "Enter the message the agent will say before ending the session...",
    triggerEventPlaceholder: "Select an event",
    createPath: "Create Track",
    editPath: "Edit Track",
    addSimulationToPath: "Add simulations to track",
    addSelected: "Add selected",
    addSimulation: "Add Simulation",
    noSimulationsAddedYet: "No simulations added yet",
    minScore: "Minimum score",
    minScoreTooltip: "Minimum score required to complete this simulation",
    addMessage: "Add Message",
    add: "Add",
    editMessage: "Edit Message",
    message: "Message",
    saveSimulation: "Simulation changes saved successfully!",
    noSimulationFound: "No simulations found",
    editPathwayDescription:
      "Are you sure you want to edit this Tracks? This will be moved to draft state.",
    eventCreatedSuccessfully: "Event created successfully",
    eventsDeletedSuccessfully: "Events deleted successfully",
    viewOnly: "View Only",
    viewOnlyTooltip: "The simulation track is currently being used.",
    viewOnlyTooltipCase: "The simulation case is currently being used.",
    create: "Create:",
    customFieldLimit: "You can only have 3 custom fields. Remove one to add another.",
    newField: "New custom field",
    triggerCondition: "Trigger conditions",
    maxTimeError(minTime: string, maxTime: string) {
      return `Maximum time must be in HH:MM:SS format between ${minTime} and ${maxTime}.`;
    },
    newRow: "New row",
    statesInstruction: "States Instruction & Dialogues",
    behavioursInstruction: "Behaviour Instructions",
    scoringRubric: "Scoring Rubric",
    ImageLibrary: "Image Library",
    imageLibrary: "Image Library",
    selectImage: "Select image",
    noImagesAvailable: "No images available",
    imageLibraryEmpty: "The image library is currently empty",
    reportGenerationInProgress: "report generation is in progress",
    reportGenerationCancelled: "report generation is cancelled",
    reportGenerationComplete: "report generation complete",
    noReportGeneration: "No report generation",
    uploadCancelConfirmation: "Your upload is not complete. Would you like to cancel the upload?",
    continueUpload: "Continue Upload",
    cancelUpload: "Cancel Upload",
    regenerate: "Regenerate",
    generate: "Generate",
    generating: "Generating...",
    regeneratedSuccessfully: "generated successfully",
    enhance: {
      trigger: "Improve",
      enhancing: "Improving...",
      modelLabel: "Model",
      customPlaceholder: "Describe how to improve, or leave blank to auto-improve…",
      customSubmit: "Apply",
      enhancedSuccessfully: "improved successfully",
    },
    generatedFillersAllCount: (n: number) => `Generated filler words for ${n} language(s)`,
    bulkGenerateNoSamples:
      "No linguistic style samples were saved. The model may have returned empty results—try again or edit manually.",
    bulkGenerateNoFillers:
      "No filler words were saved. The model may have returned empty results—try again or edit manually.",
    generatedOpeningDialoguesAllCount: (n: number) =>
      `Generated opening dialogues for ${n} language(s)`,
    bulkGenerateNoOpeningDialogues:
      "No opening dialogues were saved. The model may have returned empty results—try again or edit manually.",
    allowedFillersSectionTitle: "Allowed filler words",
    guardrails: "Guardrails",
    deleteCharacter: "Delete character",
    addStateName: "Add State Name",
    agentBuilder: {
      tabTitle: "Agent Builder Copilot",
    },
  },
  notification: {
    beforeYouGetStarted: "Before you get started",
    botDelayMessage:
      "At times, the bot may be unresponsive, or have unusual lag times. We are always working to improve the experience!",
    startSession: "Start Session",
  },
  superAdmins: {
    title: "Super Admins",
    subtitle:
      "Manage the platform's super admins — add new ones, and promote to or demote from the elevated super duper admin tier.",
    promote: "Promote",
    addSuperAdmin: "Add super admin",
    demote: "Demote",
    remove: "Remove",
    name: "Name",
    email: "Email",
    status: "Status",
    tier: "Tier",
    tierSuperAdmin: "Super admin",
    tierSuperDuperAdmin: "Super duper admin",
    addedOn: "Added on",
    searchPlaceholder: "Search by name or email",
    noAdminsFound: "No super admins found",
    noAdminsSubtitle: "Add a super admin to get started",
    noEligibleUsers: "No eligible users",
    noEligibleUsersSubtitle:
      "Every active user is already in the super-admin tier, or none match your search.",
    addConfirmTitle: "Add super admin?",
    addConfirmDescription: (name: string) =>
      `**${name}** will become a super admin with platform-wide administrative access. Their existing roles are kept.`,
    promoteConfirmTitle: "Promote to super duper admin?",
    promoteConfirmDescription: (name: string) =>
      `**${name}** will move from super admin to the elevated super duper admin tier, including access to this page.`,
    demoteConfirmTitle: "Demote super duper admin?",
    demoteConfirmDescription: (name: string) =>
      `**${name}** will be demoted back to super admin and lose access to super-duper-admin-only areas.`,
    removeConfirmTitle: "Remove super admin?",
    removeConfirmDescription: (name: string) =>
      `**${name}** will lose the super admin role and its platform-wide access. Their other roles are kept.`,
    addSuccess: "User added as super admin",
    addError: "Failed to add super admin",
    promoteSuccess: "User promoted to super duper admin",
    promoteError: "Failed to promote user",
    demoteSuccess: "User demoted to super admin",
    demoteError: "Failed to demote user",
    removeSuccess: "Super admin role removed",
    removeError: "Failed to remove super admin",
    loading: "Loading super admins...",
    cancel: "Cancel",
    confirm: "Confirm",
    you: "You",
  },
  userManagement: {
    organizationCreated: "Organization created successfully",
    organizationUpdated: "Organization updated successfully",
    failedUpdateOrganization: "Failed to update organization",
    addOrganization: "Add organization",
    users: "Users",
    organizations: "Organizations",
    userManagement: "User Management",
    createUserBadge: "Create new badge",
    userBadges: "User Badges",
    noBadgesFound: "No badges found",
    noBadgesSubtitle: "Create your first badge to get started",
    noSearchResults: "No badges match your search",
    noFilterResults: "No badges match your filters",
    organization: "Organization",
    description: "Description",
    createdOn: "Created on",
    noOfUsers: "No of users",
    user: "User",
    telephonyId: "Telephony ID",
    role: "Role",
    credits: "Credits",
    addedOn: "Added on",
    status: "Status",
    active: "Active",
    suspended: "Suspended",
    addUser: "Add user",
    bulkAddUsers: "Bulk add",
    bulkAddUsersTitle: "Bulk Add Users",
    bulkAddUsersSuccess: (count: number) =>
      `${count} ${count === 1 ? "user" : "users"} added successfully`,
    bulkAddUsersFailed: "Failed to add users",
    bulkAddUsersEmptyError: "Enter at least one email address",
    bulkAddUsersHint:
      "Users are created without a name — they'll be asked to complete their profile on first login.",
    search: "Search",
    addFilter: "Filter",
    view: "View",
    noOrganization: "No organization found",
    noOrganizationSubtitle:
      "There are no organizations found with selected filters or search query",
    noOrganizationActionLabel: "Add New Organization",
    noUsers: "There are no users found",
    noUsersSubtitle: "There are no users found with selected filters or search query",
    noUsersActionLabel: "Add New User",
    cancel: "Cancel",
    editDetails: "Edit Details",
    changeRole: "Change User Role",
    impersonateUser: "Impersonate User",
    suspendUserConfirmation: (name: string) =>
      `Are you sure you want to suspend "**${name}**"? They won't be able to log in until reactivated.`,
    removeUserConfirmation: (name: string) =>
      `Are you sure you want to remove "${name}"? This action cannot be undone.`,
    impersonateUserConfirmation: (name: string) =>
      `Are you sure you want to impersonate "${name}"? This will open a new window where you will be logged in as this user. Make sure to log out and close the window when you're done impersonating.`,
    suspendUser: "Suspend User",
    removeUser: "Remove User",
    manageCredit: "Manage Simulation Credits",
    deleteOrganization: "Delete Organization",
    deleteOrganizationConfirmation: (name: string) =>
      `Are you sure you want to remove "${name}"? This action cannot be undone.`,
    select: "Select",
    editOrganization: "Edit Organization",
    confirm: "Confirm",
    impersonate: "Impersonate",
    selectOrg: "Select Organization",
    grantAccess: "Grant Access",
    grantAccessConfirmation: (name: string) =>
      `Are you sure you want to grant access to "**${name}**"? They will be able to log in and use the system.`,
    consumedCredits: "Consumed credits",
    newCreditLimit: "New credit limit",
    oneCreditInMin: "1 credit = 1 min",
    creditsUsage: "Credits usage",
    currentRoles: "Current roles:",
    textAreaUpperLimit: "Maximum 500 characters allowed",
    maxCharError: (count: number) => `Maximum ${count} characters allowed`,
    changeRoleErrorMessage: "At least one role must be selected",
    creditRequiredError: "Credit details are required",
    creditNotNegativeError: "Credits cannot be negative",
    creditLimitError: "Maximum credit limit is 10,000",
    code: "Code",
    simulations: "Simulations",
    path: "Tracks",
    cases: "Cases",
    badges: "Badges",
    access: "Access",
    all: "All",
    enabled: "Enabled",
    disabled: "Disabled",
    filterByAccess: "Filter by access",
    toggleAccess: (title: string) => `Toggle access for ${title}`,
    userRemoved: "User removed successfully",
    logo: "Logo",
    logoDescription: " PNG or JPG files only (240x240 preferred)",
    uploadLogo: "Upload logo",
    changeLogo: "Change logo",
    uploadImage: "Upload image",
    changeImage: "Change image",
    scribeSettings: "Scribe settings",
    simulationSettings: "Simulation analytics",
    additionalFields: "Additional fields",
    configureSimulationSettings: "Configure scribe fields",
    customFields: "Custom fields",
    customFieldsEnabled: "Enable custom fields",
    scribeNoteCreationEnabled: "Enable manual note creation",
    voiceNoteEnabled: "Enable voice note (mic dictation)",
    customFieldTypes: "Custom field types",
    singleSelectFieldType: "Single select",
    multiSelectFieldType: "Multi select",
    dateFieldType: "Date",
    textFieldType: "Text",
    numberFieldType: "Number",
    booleanFieldType: "Yes / No",
    failedToUpdateScribeSettings: "Failed to update scribe settings",
    clearAll: "Clear all",
    selectAll: "Select all",
    selectedCount: (selectedCount: number, totalCount: number) =>
      `${selectedCount} of ${totalCount} selected`,
    saving: "Saving...",
    scribeSettingsNotEnabled: "Scribe settings is not enabled",
    adminFor: "Admin for:",
    addOrganizationLabel: "+ Add Organization",
    noAssignedOrganizations: "No organizations assigned yet",
    assignOrganizationSuccess: "Organization(s) assigned successfully",
    assignOrganizationError: "Failed to assign organization(s)",
    removeOrganizationSuccess: "Organization removed successfully",
    removeOrganizationError: "Failed to remove organization",
    remove: "Remove",
    selectOrganizations: "Select organizations to assign",
    noOrganizationsToAdd: "All organizations already assigned",
  },
  eventConfiguration: {
    selectEvent: "Select an event",
    searchEvents: "Search events...",
    occurred: "Occurred",
    if: "if",
    has: "has",
    more: "+more",
    addBase: "Add Branch",
  },
  knowledgeSource: {
    label: "Knowledge Sources",
    tabs: "Tabs",
    search: "Search",
    title: "Title",
    content: "Content",
    untitled: "Untitled",
    addNewTab: "Add document",
    remove: "Remove",
    deleteContent: "Delete content",
    selectTabToViewContent: "Select a tab to view content",
    noKnowledgeSourcesAdded: "No knowledge sources added yet",
    createKnowledgeSource: "Create Knowledge Source",
    enterTitle: "Enter title",
    enterContent: "Enter content",
    titleAndContentRequired: "Please enter a title and content",
  },
  badge: {
    badgeAddedToTenant: "Badge added to tenant successfully",
    badgeRemovedFromTenant: "Badge removed from tenant successfully",
    deleteBadgesConfirmation: "Delete these",
    deleteBadgesConfirmationDescription:
      "This will permanently delete the badges and remove them from all organizations and users who have already earned them. This action cannot be undone.",
    createBadge: "Create Badge",
    editBadge: "Edit Badge",
    newBadgeName: "New Badge",
    name: "Name",
    enterName: "Add name",
    description: "Description",
    enterDescription: "Add description",
    category: "Category",
    role: "Role",
    status: "Status",
    selectStatus: "Select status",
    visibility: "Default org-level visibility",
    selectVisibility: "Select visibility",
    roles: "Roles",
    addRole: "Add role",
    icon: "Icon",
    uploadIcon: "Upload Icon",
    changeIcon: "Change Icon",
    iconUploadHint: "PNG or JPG files only (240x240 preferred)",
    iconMustBeImageFile: "Icon must be a PNG or JPG file",
    iconFileTooLarge: "Icon file must be less than 2MB",
    iconMustBeSquare: "Please upload an icon with 1:1 aspect ratio",
    iconUploadFailed: "Failed to upload icon",
    uploading: "Uploading...",
    cannotChangeAfterPublishing: "Cannot be changed after publishing",
    nameRequired: "Badge name is required",
    badgeAlreadyPublished: "Badge is already published",
    badgeIconDeletedSuccessfully: "Badge icon deleted successfully",
    noChangesToSave: "No changes to save",
    unsavedChanges: "Unsaved Changes",
    unsavedChangesDescription: "You have unsaved changes. Are you sure you want to close?",
    closeAnyway: "Close Anyway",
    keepEditing: "Keep Editing",
    badgeCreatedSuccessfully: "Badge created successfully",
    badgeUpdatedSuccessfully: "Badge updated successfully",
    badgeSavedAsDraft: "Badge saved as draft",
    badgePublishedSuccessfully: "Badge published successfully",
    badgeCreationFailed: "Failed to create badge",
    badgeUpdateFailed: "Failed to update badge",
    deleteBadge: "Delete",
    deleteBadgeConfirmation: "Delete this",
    deleteBadgeConfirmationTitleItalic: " Badge?",
    deleteBadgesConfirmationTitleItalic: " Badges?",
    deleteBadgeConfirmationDescription:
      "This will permanently delete the badge and remove it from all organizations and users who have already earned it. This action cannot be undone.",
    badgeDeletedSuccessfully: "Badge deleted successfully",
    badgesDeletedSuccessfully: "Badges deleted successfully",
    saveAsDraft: "Save as draft",
    publish: "Publish",
    badgeDeletionFailed: "Failed to delete badge",
    publishBadgeConfirmation: "Publish this",
    publishBadgeConfirmationTitleItalic: " Badge?",
    publishBadgeConfirmationDescription:
      "Are you sure you want to publish this badge? Once published, this badge will be awarded to users who meet the defined criteria. ",
  },
  roleplayStudio: {
    navLabel: "Roleplay Studio",
    title: "Roleplay Studio",
    subtitle: "Design state-driven roleplay personas with the copilot",
    newRoleplay: "New Roleplay",
    untitledRoleplay: "Untitled roleplay",
    open: "Open",
    delete: "Delete",
    deleteTitle: "Delete this",
    deleteTitleItalic: "Roleplay?",
    deleteDescription:
      "This will permanently delete the roleplay spec, its versions, and its rehearsal history. This action cannot be undone.",
    emptyTitle: "No roleplays yet",
    emptySubtitle: "Create your first roleplay and let the copilot interview you into a spec.",
    loadFailed: "Failed to load roleplays",
    createFailed: "Failed to create roleplay",
    deleteFailed: "Failed to delete roleplay",
    duplicate: "Duplicate",
    duplicating: "Duplicating…",
    duplicateFailed: "Failed to duplicate roleplay",
    copyOfPrefix: "Copy of ",
    columns: {
      title: "Title",
      status: "Status",
      updatedAt: "Last updated",
      actions: "",
    },
    steps: {
      chat: "Chat",
      spec: "Spec",
      publish: "Publish",
    },
    workbench: {
      specView: "Spec",
      stateMachineView: "State machine",
      copilotManaged: "Copilot-managed — only voice toggles are editable",
      editToggle: "Edit spec directly",
      editingHint: "Direct edits autosave",
      editLockedHint: "Editing is paused while the copilot is active",
    },
    autosave: {
      saving: "Saving…",
      saved: "Draft saved",
      failed: "Couldn’t save — retrying shortly",
      conflict: "Newer draft on server — reloaded",
    },
    titlePlaceholder: "Name this roleplay",
    copilot: {
      title: "Copilot",
      placeholder: "Describe the persona, scenario, or ask for changes…",
      send: "Send",
      stop: "Stop",
      interrupted: "(interrupted)",
      thinking: "Thinking…",
      resumeFailed: "Couldn’t resume the copilot session",
      startFailed: "Couldn’t start a copilot session",
      streamFailed: "The copilot stream failed — please try again",
      emptyTitle: "Start the interview",
      emptySubtitle:
        "Tell the copilot who the trainee will be talking to. It will draft the persona, states, secrets, and rubric live on the right.",
      toolRunning: "Working",
      answer: "Answer",
      submitAnswer: "Submit answer",
      freeTextPlaceholder: "Type your answer…",
      confirmSelection: "Confirm",
      noneOfThese: "None of these",
      addCustom: "Add your own",
      addCustomPlaceholder: "Add your own…",
      add: "Add",
      selectPlaceholder: "Select…",
      minSelectionsHint: (n: number) => `Select at least ${n}`,
      behaviourReviewHelpful: "Helpful behaviours",
      behaviourReviewUnhelpful: "Unhelpful behaviours",
      behaviourReviewConfirm: "Confirm behaviours",
      behaviourReviewEmpty: "No behaviours selected yet",
      selectedCountLabel: (n: number) => `${n} selected`,
    },
    spec: {
      personaBible: "Persona Bible",
      identityCore: "Identity core",
      scenarioContext: "Scenario context",
      chunks: "Persona chunks",
      addChunk: "Add chunk",
      chunkTopics: "Topics (comma separated)",
      chunkContent: "Content",
      stateMachine: "State Machine",
      disclosureLedger: "Disclosure Ledger",
      addSecret: "Add secret",
      secretTopic: "Topic",
      secretContent: "Content",
      secretUnlockConditions: "Unlock conditions",
      secretLockedDeflection: "Locked deflection",
      secretTier: "Tier",
      rubric: "Rubric",
      addBehavior: "Add behavior",
      behaviorName: "Name",
      behaviorDescription: "Description",
      behaviorWeight: "Weight",
      behaviorExamples: "Examples",
      polarityPositive: "Positive",
      polarityNegative: "Negative",
      engineeredEvents: "Engineered Events",
      addEvent: "Add event",
      eventName: "Name",
      eventDescription: "Description",
      voiceAndLanguage: "Voice & Language",
      languages: "Languages the actor can be played in",
      languagesPlaceholder: "Select one or more languages",
      voicesPerLanguage: "Voice per language",
      voicePending: "Voice assigned by the copilot",
      openingStatement: "Opening statement",
      difficulty: "Difficulty",
      voiceNaturalness: "Voice Naturalness",
      thinkingFiller: "Thinking Filler",
      thinkingFillerHelp:
        "Play a brief 'thinking' sound the instant the learner stops speaking, masking reply latency.",
      comfortAudio: "Comfort Audio",
      comfortAudioHelp:
        "Loop a faint ambient room tone so the line never sounds dead between turns.",
      continuousBackchanneling: "Continuous Back-channeling",
      continuousBackchannelingHelp:
        'Play brief listener affirmations ("mm-hmm") while the learner speaks on long turns.',
      interimReply: "Interim Reply",
      interimReplyHelp:
        "Speak a short holding reply from the partial transcript while the learner finishes, then cut to the real reply.",
      emptySection: "Nothing here yet — the copilot fills this in during the interview.",
      remove: "Remove",
    },
    stateMachine: {
      addState: "Add state",
      maxStatesTooltip: "A roleplay supports at most 6 states",
      minStatesTooltip: "A roleplay needs at least 3 states",
      editState: "Edit state",
      editTransition: "Edit transition",
      deleteStateTitle: "Delete this",
      deleteStateTitleItalic: "State?",
      deleteStateDescription: "Deleting this state also removes the transitions listed below.",
      orphanedTransitions: "Transitions that will be removed:",
      noOrphanedTransitions: "No transitions reference this state.",
      stateName: "Name",
      emotionalRegister: "Emotional register",
      disclosurePosture: "Disclosure posture",
      resistanceLevel: "Resistance level",
      stateCard: "State card",
      defaultStageDirection: "Default stage direction",
      prosodyHints: "Prosody hints",
      initialState: "Initial state",
      transitionDescription: "Description",
      whenBehaviorsAny: "When any of these behaviors",
      whenBehaviorsAll: "When all of these behaviors",
      minTurnsInState: "Min turns in state",
      minCumulativeScore: "Min cumulative score",
      toState: "To state",
      readOnly: "Read-only",
      viewJourney: "Journey",
      viewOutline: "Outline",
      viewCanvas: "Canvas",
      viewLabel: "State machine view",
      addTransition: "Add transition",
      addTransitionFrom: "Add a transition from this state",
      deleteState: "Delete state",
      transitionTo: (name: string) => `Advances to ${name}`,
      skipsTo: (name: string) => `Skips ahead to ${name}`,
      returnsTo: (name: string) => `Falls back to ${name}`,
      loopsOn: "Stays in this state",
      unknownTarget: "missing state",
      danglingTransition: "Points at a deleted state",
      unreachable: "Not reachable from the initial state",
      guardAnyOf: (names: string) => `any of: ${names}`,
      guardAllOf: (names: string) => `all of: ${names}`,
      guardMinTurns: (n: number) => `≥${n} turn${n === 1 ? "" : "s"} in state`,
      guardMinScore: (n: number) => `score ≥ ${n}`,
      guardAlways: "always (no conditions)",
      outgoingTransitions: "Leads to",
      incomingTransitions: "Reached from",
      noOutgoingTransitions: "No transitions out of this state yet.",
      noIncomingTransitions: "Nothing transitions into this state.",
      arcHint: "The client's emotional arc, from the opening state onward.",
    },
    publish: {
      title: "Publish",
      readiness: "Readiness checklist",
      checkStates: "3–6 states in the state machine",
      checkSecret: "At least one secret in the disclosure ledger",
      checkRubric: "Rubric has at least one behavior",
      checkVoice: "A voice is selected",
      versions: "Versions",
      publish: "Publish",
      publishing: "Publishing…",
      published: "Version published",
      publishFailed: "Failed to publish version",
      newVersion: "New version",
      tryLive: "Try live",
      preview: "Preview",
      previewLanguage: "Preview language",
      previewHint: "Add 3–6 states and a voice to preview the draft",
      publishHint: "Complete the readiness checklist to publish",
      startingSession: "Starting session…",
      sessionFailed: "Failed to start a live session",
      noVersions: "No versions yet",
    },
    improve: {
      button: "Improve",
      buttonHint: "Add 3–6 states and a voice to run test cases",
      drawerTitle: "Improve",
      drawerSubtitle:
        "Run agent test cases against the current draft, then feed a report back to the copilot to fix the spec.",
      testCasesHeading: "Test cases",
      searchPlaceholder: "Filter test cases…",
      noTestCases: "No agent test cases yet — create some under Agent Test Cases first.",
      noMatchingTestCases: "No test cases match this filter.",
      loadTestCasesFailed: "Failed to load test cases",
      typeCondition: "Condition",
      typeFullSession: "Full session",
      runTestCases: (n: number) => `Run test cases (${n})`,
      startingRun: "Starting…",
      runInProgressHint: "A test run is already in progress",
      selectCasesHint: "Select at least one test case",
      runStarted: "Test run started",
      runStartFailed: "Failed to start the test run",
      reportsHeading: "Test reports",
      reportsEmpty: "No test reports yet — select test cases above and run them.",
      loadReportsFailed: "Failed to load test reports",
      pending: "Running…",
      progressLabel: (completed: number, total: number) => `${completed}/${total} complete`,
      cancelRun: "Cancel run",
      runCancelled: "Test run cancelled",
      cancelFailed: "Failed to cancel the test run",
      statusFailed: "Failed",
      statusCancelled: "Cancelled",
      verdictPassed: "Passed",
      verdictFailed: "Failed",
      verdictInconclusive: "Inconclusive",
      versionLabel: (n: number | string) => `v${n}`,
      autoImprove: "Auto improve",
      autoImproveHint:
        "Send this report to the copilot; it patches the spec, then the same test case re-runs",
      autoImproveQueued: "Sent to the copilot — watch it patch the spec in Chat",
      autoImprovePrompt: (title: string) =>
        `Auto-improve the spec from the test report for "${title}".`,
      autoImproveRejected:
        "Auto-improve was rejected — the report is already improving or a run is in flight",
      turnInProgress: "The copilot is already mid-turn — try again once it finishes",
      improving: "Improving…",
      rerunning: "Re-running…",
      noChanges: "Copilot made no changes — see its explanation in Chat",
      improveFailed: "Auto-improve failed",
      improvedFrom: "Improved from an earlier report",
      overallScore: "Overall score",
      rubricScores: "Rubric scores",
      sessionQuality: "Session quality",
      judgeNotes: "Judge notes",
      reportSection: "Report",
      transcript: "Transcript",
      showTranscript: "Show transcript",
      hideTranscript: "Hide transcript",
      detailLoadFailed: "Failed to load the report",
      noReportContent: "No report content available.",
    },
    preview: {
      directorFeed: "Director feed",
      turn: "Turn",
      behaviors: "Behaviors",
      stateChange: "State",
      unlocks: "Unlocks",
      score: "Score",
      feedback: "Feedback",
      stale: "stale",
      waiting: "Waiting for the director…",
    },
    saveConflict: "Someone else saved this draft — reloaded the latest version",
  },
  tooltip: {
    scenarioTooltips: "Tooltips",
    createTooltip: "Create Tooltip",
    editTooltip: "Edit Tooltip",
    searchTooltips: "Search tooltips...",
    tipText: "Tip Text",
    status: "Status",
    locationRequired: "Location and tip text are required",
    tipTextTooLong: "Tip text must be 200 characters or less",
    unsavedChangesWarning: "You have unsaved changes. Are you sure you want to close?",
    tooltipCreated: "Tooltip created successfully",
    tooltipUpdated: "Tooltip updated successfully",
    locationAlreadyExists: "A tooltip for this location already exists",
  },
  comfortAudio: {
    title: "Comfort Audio",
    description:
      "Upload ambient audio tracks that scenario authors can play as comfort audio under a roleplay so the line never sounds dead between turns.",
    uploadNamePlaceholder: "Track name",
    chooseFile: "Choose audio file",
    upload: "Upload",
    uploading: "Uploading...",
    nameRequired: "Enter a name for the track",
    fileRequired: "Choose an audio file to upload",
    invalidFileType: "File must be an MP3, WAV, or M4A audio file",
    fileTooLarge: "Audio file must be under 20 MB",
    uploadSuccess: "Comfort audio track uploaded",
    uploadFailed: "Failed to upload comfort audio track",
    deleteSuccess: "Comfort audio track deleted",
    deleteFailed: "Failed to delete comfort audio track",
    empty: "No comfort audio tracks uploaded yet",
    listError: "Failed to load comfort audio tracks",
    // Manage existing tracks (Settings)
    rename: "Rename",
    renamePlaceholder: "Track name",
    save: "Save",
    cancel: "Cancel",
    renameSuccess: "Comfort audio track renamed",
    renameFailed: "Failed to rename comfort audio track",
    archive: "Archive",
    unarchive: "Unarchive",
    archivedBadge: "Archived",
    archivedHelp:
      "Archived tracks can't be selected for new roleplays but keep playing for roleplays already using them.",
    archiveSuccess: "Comfort audio track archived",
    archiveFailed: "Failed to archive comfort audio track",
    unarchiveSuccess: "Comfort audio track unarchived",
    unarchiveFailed: "Failed to unarchive comfort audio track",
    archivedOptionSuffix: " (archived)",
    // Basic Settings picker
    trackLabel: "Comfort Audio Track",
    trackPlaceholder: "Select a track (default room tone if unset)",
    volumeLabel: "Comfort Audio Volume",
    volumeHelp: "How loud the comfort audio plays under the conversation (0 = silent, 1 = full).",
    preview: "Preview",
    stop: "Stop",
    loadingTracks: "Loading tracks...",
    noTracks: "No tracks available — a superadmin can upload them in Settings.",
  },
  aiLab: {
    title: "AI Lab",
    tabs: {
      skills: "Skills",
      variables: "Variables",
      values: "Values",
      runs: "Runs",
      evaluators: "Evaluators",
      questionSets: "Question Sets",
    },
    // Skills
    skills: {
      heading: "Skills",
      subtitle:
        "Reusable system-prompt templates. Reference variables as {{name}} to be filled in at run time.",
      searchPlaceholder: "Search skills...",
      create: "New Skill",
      edit: "Edit Skill",
      namePlaceholder: "Skill name",
      nameLabel: "Name",
      descriptionLabel: "Description",
      descriptionPlaceholder: "What does this skill do?",
      contentLabel: "System Prompt",
      contentPlaceholder: "You are a helpful assistant. Use {{variable}} placeholders…",
      modelLabel: "Model",
      modelHelp: "The AI model this skill runs on.",
      temperatureLabel: "Temperature",
      temperatureHelp:
        "0–2. Leave blank for the provider default. Ignored by models that don't support it.",
      temperaturePlaceholder: "e.g. 0.7",
      maxTokensLabel: "Max output tokens",
      maxTokensHelp: "Cap on the response length. Leave blank for the AI Lab default.",
      maxTokensPlaceholder: "e.g. 2048",
      systemPromptLabel: "System prompt (optional)",
      systemPromptHelp: "Sent as a separate system message alongside the resolved prompt below.",
      systemPromptPlaceholder: "You are a strict JSON generator…",
      invalidTemperature: "Temperature must be between 0 and 2",
      invalidMaxTokens: "Max tokens must be a positive whole number",
      empty: "No skills yet",
      emptySubtitle: "Create a system-prompt template to reuse across runs.",
      created: "Skill created",
      updated: "Skill updated",
      deleted: "Skill deleted",
      saveFailed: "Failed to save skill",
      deleteFailed: "Failed to delete skill",
      deleteTitle: "Delete skill?",
      deleteDescription: "This permanently removes the skill. This cannot be undone.",
      validation: "Name and system prompt are required",
    },
    // Variables
    variables: {
      heading: "Variables",
      subtitle:
        "Unique placeholder names used in skill templates as {{name}} and replaced with a value at run time.",
      searchPlaceholder: "Search variables...",
      create: "New Variable",
      edit: "Edit Variable",
      nameLabel: "Name",
      namePlaceholder: "e.g. customer_tone",
      nameHelp: "Letters, digits, underscore, dot or dash. No spaces.",
      descriptionLabel: "Description",
      descriptionPlaceholder: "What does this variable represent?",
      empty: "No variables yet",
      emptySubtitle: "Define placeholder names you can drop into skill prompts.",
      created: "Variable created",
      updated: "Variable updated",
      deleted: "Variable deleted",
      saveFailed: "Failed to save variable",
      deleteFailed: "Failed to delete variable",
      deleteTitle: "Delete variable?",
      deleteDescription:
        "This permanently removes the variable and all of its values. This cannot be undone.",
      duplicate: "A variable with this name already exists",
      validation: "A valid name is required",
    },
    // Values
    values: {
      heading: "Values",
      subtitle: "Candidate values bound to variables, substituted into templates at run time.",
      searchPlaceholder: "Search values...",
      create: "New Value",
      edit: "Edit Value",
      variableLabel: "Variable",
      variablePlaceholder: "Select a variable",
      labelLabel: "Label",
      labelPlaceholder: "Optional friendly label",
      valueLabel: "Value",
      valuePlaceholder: "The substitution value",
      columnVariable: "Variable",
      columnLabel: "Label",
      columnValue: "Value",
      empty: "No values yet",
      emptySubtitle: "Add values for your variables so runs have something to substitute.",
      noVariables: "Create a variable first — values are bound to a variable.",
      created: "Value created",
      updated: "Value updated",
      deleted: "Value deleted",
      saveFailed: "Failed to save value",
      deleteFailed: "Failed to delete value",
      deleteTitle: "Delete value?",
      deleteDescription: "This permanently removes the value. This cannot be undone.",
      validation: "A variable and a value are required",
    },
    // Runs
    runs: {
      heading: "Runs",
      subtitle:
        "Execute skills with variable values substituted in. Each skill in a run is logged as its own row.",
      create: "Create New Run",
      searchPlaceholder: "Search runs...",
      empty: "No runs yet",
      emptySubtitle: "Create a run to execute one or more skills and see their output here.",
      // Drawer
      drawerTitle: "Create New Run",
      selectSkills: "Select skills",
      selectSkillsHelp: "Pick one or more skills to run.",
      noSkills: "Create a skill first — runs execute skills.",
      variablesHeading: "Variable values",
      variablesHelp:
        "Choose one or more values for each variable — every combination is run (a matrix).",
      noVariablesNeeded: "The selected skills use no variables.",
      missingValues: "Some variables have no values yet — add values in the Values tab.",
      matrixSummary: "{runs} run(s) will be created.",
      tooManyRuns: "That's {runs} runs — reduce selections to {max} or fewer.",
      run: "Run",
      running: "Running…",
      runningProgress: "Running {done} of {total}…",
      validationSkills: "Select at least one skill",
      validationValues: "Select a value for every variable",
      runsComplete: "Run complete",
      runsFailed: "Run failed",
      runsPartial: "{failed} of {total} runs failed",
      failuresTitle: "Some runs didn't complete",
      failuresHelp:
        "The skills below failed to run (a network or request error). Close to review the log, or dismiss to try again.",
      dismissFailures: "Back to form",
      close: "Close",
      // Table columns
      columnSkill: "Skill",
      columnVariables: "Variables",
      columnModel: "Model",
      columnStatus: "Status",
      columnOutput: "Output",
      columnCreated: "Created",
      // Detail viewer
      detailTitle: "Run detail",
      detailSkill: "Skill",
      detailModel: "Model",
      detailStatus: "Status",
      detailVariables: "Variables",
      detailPrompt: "Resolved prompt",
      detailOutput: "Output",
      detailError: "Error",
      detailTokens: "Tokens",
      detailCost: "Est. cost",
      deleted: "Run deleted",
      deleteFailed: "Failed to delete run",
      deleteTitle: "Delete run?",
      deleteDescription: "This permanently removes the run from the log. This cannot be undone.",
      paginationRange: "Showing {start}–{end} of {total}",
      prev: "Previous",
      next: "Next",
      // Bulk selection
      selectedCount: (count: number) => `${count} selected`,
      clearSelection: "Clear selection",
      bulkPublishAction: "Add Questions & Publish",
      bulkAssignAction: "Manage Evaluators",
    },
    // Bulk: add questions/question sets and publish several runs at once
    bulkPublish: {
      drawerTitle: "Publish Selected Runs",
      subtitle: (count: number) =>
        `Attach the same evaluation questions to ${count} selected run${count === 1 ? "" : "s"}. At least one question is required. Questions cannot be changed after publishing.`,
      publishButton: "Publish All",
      publishing: "Publishing…",
      validation: "Add at least one question and fill in every question text",
      allSucceeded: (count: number) =>
        `${count} run${count === 1 ? "" : "s"} published for evaluation`,
      partialFailure: (failed: number, total: number) =>
        `${failed} of ${total} runs failed to publish — the rest were published`,
      allFailed: "Failed to publish the selected runs",
    },
    // Bulk: add/remove human evaluators across several published runs at once
    bulkAssign: {
      drawerTitle: "Manage Evaluators",
      subtitle: (count: number) =>
        `Add or remove human evaluators across ${count} selected published run${count === 1 ? "" : "s"}.`,
      noEvaluators: "No evaluators yet — create them in the Evaluators tab first.",
      assignedAll: "Assigned to all selected",
      assignedSome: (assigned: number, total: number) => `Assigned to ${assigned} of ${total}`,
      assignedNone: "Not assigned to any selected run",
      apply: "Apply Changes",
      applying: "Applying…",
      noChanges: "Change at least one evaluator's assignment before applying",
      added: (count: number) => `${count} assignment${count === 1 ? "" : "s"} added`,
      removed: (count: number) => `${count} assignment${count === 1 ? "" : "s"} removed`,
      skippedSubmitted: (count: number) => `${count} skipped (already submitted)`,
      applyFailed: "Some changes failed to apply",
      loadFailed: "Failed to load current assignments",
    },
    // Automated (LLM-as-judge) evaluation
    autoEval: {
      action: "Auto-evaluate",
      drawerTitle: "Automated Evaluation",
      subtitle:
        "Score this run's output against a rubric using an LLM judge. Fast, cheap, repeatable — complements human evaluation.",
      criteriaLabel: "Criteria / rubric",
      criteriaPlaceholder:
        "e.g. The response must be valid JSON, cite a source, and stay under 100 words.",
      modelLabel: "Judge model",
      run: "Run evaluation",
      running: "Evaluating…",
      empty: "No automated evaluations yet.",
      priorHeading: "Previous evaluations",
      scoreLabel: "Score",
      failed: "Evaluation failed",
      success: "Evaluation complete",
      validation: "Enter the criteria to score against",
    },
    // Publish for human evaluation
    publish: {
      action: "Publish",
      drawerTitle: "Publish for Human Evaluation",
      subtitle:
        "Attach the evaluation questions human evaluators will answer for this record. At least one question is required. Questions cannot be changed after publishing.",
      addQuestion: "Add Question",
      questionLabel: "Question",
      questionPlaceholder: "e.g. How helpful is this response?",
      typeLabel: "Type",
      typeRating: "Rating scale",
      typeYesNo: "Yes / No",
      typeText: "Open-ended text",
      typeDescription: "Description (no response needed)",
      scaleLabel: "Scale",
      scaleOption: (max: number) => `1 to ${max}`,
      remove: "Remove",
      publishButton: "Publish",
      validation: "Add at least one question and fill in every question text",
      published: "Run published for evaluation",
      publishFailed: "Failed to publish run",
      publishedBadge: "Published",
    },
    // Assign evaluators
    assign: {
      action: "Assign evaluators",
      drawerTitle: "Assign Evaluators",
      subtitle:
        "Pick the human evaluators who should review this record. Submitted evaluations cannot be unassigned.",
      noEvaluators: "No evaluators yet — create them in the Evaluators tab first.",
      submittedLock: "Submitted",
      save: "Save assignments",
      saved: "Assignments updated",
      saveFailed: "Failed to update assignments",
      responses: (submitted: number, assigned: number) => `${submitted}/${assigned} responses`,
    },
    // Aggregated results
    results: {
      action: "View results",
      drawerTitle: "Evaluation Results",
      assigned: "Assigned",
      submitted: "Submitted",
      recordAverage: "Record score",
      recordAverageHelp:
        "Scale-agnostic average across all rating answers for this record (0-100%)",
      noRatingsYet: "No ratings yet",
      responsesLabel: "responses",
      yes: "Yes",
      no: "No",
      noTextAnswers: "No written answers yet",
      descriptionNote: "Descriptive text — no responses collected",
      evaluatorsHeading: "Evaluators",
      pending: "Pending",
      loadFailed: "Failed to load results",
      exportCsv: "Export CSV",
      exportJson: "Export JSON",
      agreement: "Agreement",
      agreementHelp:
        "Share of evaluators on the most common answer — high means raters agree, low means they're split.",
    },
    // Compare runs in a batch
    compare: {
      action: "Compare batch",
      drawerTitle: "Compare Runs",
      subtitle: "Runs from the same batch, side by side.",
      empty: "No other runs in this batch.",
      columnOutput: "Output",
      columnTokens: "Tokens",
      columnCost: "Est. cost",
    },
    // Evaluators tab
    evaluators: {
      heading: "Evaluators",
      subtitle:
        "Human evaluators sign in at /evaluate with their email and an auto-generated password you share with them offline.",
      searchPlaceholder: "Search evaluators...",
      create: "New Evaluator",
      emailLabel: "Email",
      emailPlaceholder: "evaluator@example.com",
      empty: "No evaluators yet",
      emptySubtitle: "Create evaluator accounts to assign published records for human review.",
      created: "Evaluator created",
      createFailed: "Failed to create evaluator",
      duplicate: "An evaluator with this email already exists",
      deleted: "Evaluator deleted",
      deleteFailed: "Failed to delete evaluator",
      deleteTitle: "Delete evaluator?",
      deleteDescription:
        "This permanently removes the evaluator, their assignments and their submitted answers. This cannot be undone.",
      regenerate: "Regenerate password",
      regenerated: "Password regenerated",
      regenerateFailed: "Failed to regenerate password",
      regenerateTitle: "Regenerate password?",
      regenerateDescription:
        "The current password stops working immediately and any active session is signed out. You'll get a new password to share.",
      passwordTitle: "Evaluator password",
      passwordNote:
        "Copy this password now and share it offline — it is shown only once and cannot be retrieved later.",
      copyPassword: "Copy password",
      copied: "Copied to clipboard",
      copyFailed: "Couldn't copy — select and copy the password manually",
      columnEmail: "Email",
      columnAssigned: "Assigned",
      columnSubmitted: "Submitted",
      columnLastLogin: "Last login",
      columnCreated: "Created",
      never: "Never",
      portalLinkLabel: "Evaluator portal:",
      validation: "Enter a valid email address",
    },
    // Question Sets — reusable, named lists of human-eval questions
    questionSets: {
      heading: "Question Sets",
      subtitle:
        "Reusable, named lists of human-evaluation questions. Publish a set to apply it when publishing runs for evaluation. Questions cannot be changed after publishing.",
      searchPlaceholder: "Search question sets...",
      create: "New Question Set",
      edit: "Edit Question Set",
      view: "View Question Set",
      nameLabel: "Name",
      namePlaceholder: "e.g. Onboarding tone check",
      descriptionLabel: "Description",
      descriptionPlaceholder: "What is this set used to evaluate?",
      columnName: "Name",
      columnQuestions: "Questions",
      columnStatus: "Status",
      columnCreated: "Created",
      statusDraft: "Draft",
      statusPublished: "Published",
      questionCount: (count: number) => `${count} question${count === 1 ? "" : "s"}`,
      empty: "No question sets yet",
      emptySubtitle: "Create a reusable list of questions to apply when publishing runs.",
      saveDraft: "Save Draft",
      publishButton: "Publish",
      publishHelp: "Publishing locks the question list — it can no longer be edited.",
      publishConfirmTitle: "Publish this question set?",
      publishConfirmDescription:
        "Its questions will be locked and can no longer be edited. You can still archive the set later to retire it. This cannot be undone.",
      created: "Question set created",
      updated: "Question set updated",
      published: "Question set published",
      saveFailed: "Failed to save question set",
      publishFailed: "Failed to publish question set",
      validation: "Name and at least one question (with text) are required to publish",
      draftValidation: "A name is required",
      archive: "Archive",
      unarchive: "Unarchive",
      archivedBadge: "Archived",
      archivedHelp:
        "Archived sets can't be applied to new runs but stay intact for runs that already imported their questions.",
      archiveSuccess: "Question set archived",
      archiveFailed: "Failed to archive question set",
      unarchiveSuccess: "Question set unarchived",
      unarchiveFailed: "Failed to unarchive question set",
      deleted: "Question set deleted",
      deleteFailed: "Failed to delete question set",
      deleteTitle: "Delete question set?",
      deleteDescription: "This permanently removes the draft. This cannot be undone.",
      lockedNote: "This question set is published and can no longer be edited.",
      // Reused inside the question builder (same copy as ad-hoc publish questions)
      addQuestion: "Add Question",
      questionLabel: "Question",
      questionPlaceholder: "e.g. How helpful is this response?",
      typeLabel: "Type",
      typeRating: "Rating scale",
      typeYesNo: "Yes / No",
      typeText: "Open-ended text",
      typeDescription: "Description (no response needed)",
      scaleLabel: "Scale",
      remove: "Remove",
      moveUp: "Move up",
      moveDown: "Move down",
      // Import into the run-publish drawer
      importLabel: "Import from a question set",
      importPlaceholder: "Choose a published question set…",
      importAction: "Import",
      importedNote: "Imported — you can still edit or remove these below.",
      noSets: "No published question sets yet.",
    },
    unsavedChangesWarning: "You have unsaved changes. Are you sure you want to close?",
    listError: "Failed to load AI Lab data",
  },
  // The /evaluate micro-app (human evaluators; separate from the admin session)
  analyticsAgent: {
    tabLabel: "Analytics Agent",
    heading: "Ask a question about the platform",
    // The empty state teaches rather than decorates: this is the one screen where
    // a reader has no idea what the thing can do until they have watched it work.
    emptyTitle: "Ask in plain English",
    emptySubtitle:
      "The agent writes a read-only SQL query against the analytics tables, runs it, and explains the result. It shows you the query it ran, so you can check the number.",
    inputPlaceholder: "e.g. How many simulations were completed per week in the last 90 days?",
    send: "Ask",
    sending: "Working…",
    // Named for what it does. "Clear" would read as deleting data.
    reset: "Reset chat",
    resetConfirmTitle: "Reset this chat?",
    resetConfirmBody:
      "The conversation is only held in this browser tab, so resetting it cannot be undone. Nothing stored is affected.",
    // Distinct from the trigger button's label: two controls named "Reset chat"
    // on the same screen are one ambiguous target for a screen reader, and the
    // dialog's job is to state what confirming does.
    resetConfirm: "Reset and start over",
    cancel: "Cancel",
    // Progress narrative, not a bare spinner: two model calls and a query take
    // real seconds, and a reader who cannot tell "working" from "stuck" reloads.
    pendingPlanning: "Working out which tables answer this…",
    pendingSlow: "Still working — a broad question can take up to a minute.",
    requestFailed: "The agent could not be reached. Check your connection and ask again.",
    showQuery: "Show the SQL",
    hideQuery: "Hide the SQL",
    ranIn: "ran in",
    rowsReturned: "rows",
    truncatedNotice:
      "Showing the first {count} rows — the full result is larger, so any total in the answer is a lower bound.",
    skippedRowsNotice:
      "{count} row(s) are not on the chart because the measure was missing or not a number. They are in the table.",
    caveatsTitle: "Worth knowing",
    followUpsTitle: "Ask next",
    clarifyTitle: "Needs a bit more detail",
    refusedTitle: "Can't answer that from this data",
    rejectedTitle: "Query refused",
    failedTitle: "Query didn't run",
    provenance: "Planned by {planner} · written by {answer} · prompt {version}",
    provenancePlannerOnly: "Planned by {planner} · prompt {version}",
    scopeTitle: "What can I ask about?",
    scopeIntro:
      "The agent reads aggregate analytics only. It can query these tables, capped at {rowLimit} rows per question:",
    scopeDeniedIntro:
      "It can never read credentials, personal contact details, or session and message content — including inside a count.",
    scopeLoadFailed: "Couldn't load the list of readable tables.",
    tableColumns: "columns",
    emptyResult: "The query ran and matched no rows.",
    // Sample questions in the empty state. Deliberately concrete and answerable
    // from the readable tables — a suggestion that gets refused teaches the wrong
    // lesson on a reader's first try.
    samples: [
      "How many simulations were completed each week over the last 90 days?",
      "Which 10 organisations ran the most simulations this month?",
      "What is the median simulation length, and how many sessions is that over?",
      "How has AI spend per model changed month over month this year?",
      "How many learners practised at all in the last 30 days, by organisation?",
    ],
  },
  evaluate: {
    title: "Ally Evaluation",
    loginHeading: "Evaluator Sign In",
    loginSubtitle: "Use the email and password shared with you by the Ally team.",
    emailLabel: "Email",
    passwordLabel: "Password",
    signIn: "Sign In",
    signingIn: "Signing in...",
    loginFailed: "Invalid email or password",
    signOut: "Sign out",
    recordsHeading: "Your assigned records",
    recordsSubtitle: "Open a record to review it and answer the evaluation questions.",
    noRecords: "Nothing assigned to you yet",
    noRecordsSubtitle: "When the Ally team assigns records to you, they will appear here.",
    statusPending: "Pending",
    statusSubmitted: "Submitted",
    questionsCount: (count: number) => `${count} question${count === 1 ? "" : "s"}`,
    assignedOn: "Assigned",
    back: "Back to records",
    recordHeading: "Record",
    recordIdLabel: "Record ID",
    outputHeading: "Output",
    variablesHeading: "Variables",
    questionsHeading: "Evaluation questions",
    textPlaceholder: "Write your answer...",
    descriptionHint: "For your reference — no response needed",
    yes: "Yes",
    no: "No",
    submit: "Submit evaluation",
    submitting: "Submitting...",
    submitConfirmTitle: "Submit evaluation?",
    submitConfirmDescription:
      "Answers cannot be changed after submitting. Make sure you're happy with them.",
    submitConfirm: "Submit",
    cancel: "Cancel",
    submitted: "Evaluation submitted — thank you!",
    submitFailed: "Failed to submit evaluation",
    answerAll: "Please answer every question",
    submittedOn: "Submitted",
    readOnlyNote: "This evaluation was submitted and can no longer be edited.",
    loadFailed: "Failed to load",
  },
};
