export const en = {
  common: {
    apply: "Apply",
    search: "Search",
    loading: "Loading...",
    loadMore: "Load more",
    noMoreData: "No more data",
    update: "Update",
    create: "Create",
    goBack: "Go Back",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    noOptionsAvailable: "No options available",
    noResultsFound: "No results found for",
    select: "Select",
    uploading: "Uploading...",
    enabled: "Enabled",
    disabled: "Disabled",
    edit: "Edit",
    or: "OR",
  },
  errors: {
    failedToGoogleSignIn: "Failed to sign in with Google. Please try again.",
    failedCreateOrganization: "Failed to create organization",
    fileMustBeJPEGOrPNG: "File must be JPEG or PNG.",
    fileMustBeVideo: "File must be a video.",
    fileUploadFailed: "Failed to upload file. Please try again.",
    fileMetadataLoadFailed: "Failed to load video metadata",
    imageMustHave169AspectRatio: "Image must have a 16:9 aspect ratio.",
    imageMustHave1AspectRatio: "Please upload an image with the correct aspect ratio",
    fileDeleteFailed: "Failed to delete file. Please try again.",
    titleIsRequired: "Title should be filled to save as draft",
    failedSimulationChange: "Failed to save simulation changes!",
    failedPathwayChange: "Failed to save Tracks changes!",
    failedSaveDraft: "Failed to save draft. Please try again.",
    failedSimulationCreation: "Failed to create simulation. Please try again.",
    pathUpdateFailed: "Failed to update track access.",
    failedUpdateAccess: "Failed to update access.",
    OrganizationNotFound: "Organization not found",
    minimumScoreError: "Minimum score must be a positive integer",
    failedToCreateEvent: "Failed to create event",
    failedToProceed: "Fill atleast title field to proceed to Event Configuration!",
    failedToSaveEvents: "Failed to save events. Please try again.",
    failedToDeleteEvent: "Failed to delete event. Please try again.",
    errorUpdatingEvent: "Error updating event",
    userIdNotFound: "User id not found",
    failedToRemoveUser: "Failed to remove user",
    failedToUploadImage: "Failed to upload image",
    failedToLoadImage: "Failed to load image",
  },
  accessDenied: {
    title: "This page is not accessible",
    message:
      "You don't have permission to access this page. Please contact your administrator if you believe this is an error.",
  },
  error: {
    apiRequestFailed: "API request failed",
    noRefreshDataReceived: "No refresh data received",
    tokenRefreshFailed: "Token refresh failed",
    userFetchFailed: "User fetch failed",
    permissionsFetchFailed: "Permissions fetch failed",
    authenticationFailed: "Authentication failed",
  },
  auth: {
    hey: "Hey",
    welcomeTo: "Welcome to",
    ally: "ally",
    email: "Email",
    password: "Password",
    login: "Login",
    signup: "Signup",
    forgotPassword: "Forgot Password",
    rememberMe: "Remember Me",
    generatingOTP: "Generating OTP...",
    termsAndConditions: "Terms & Conditions",
    privacyPolicy: "Privacy Policy",
    didNotReceiveTheCode: "Didn't receive the code?",
    signingIn: "Signing in...",
    logout: "Logout",
    enterEmailToContinue: "Enter your email address to continue",
    enterEmailPlaceholder: "Enter your email address",
    next: "Next",
    byTappingNext: "By tapping next, you agree to Ally's",
    andAcknowledge: "and acknowledge",
    verifyYourEmail: "Verify your email address",
    enterSecurityCode: "Enter the security code sent to",
    codeWillExpire: "This code will expire in",
    minutes: "minutes",
    needNewCode: "Need a new code?",
    resend: "Resend",
    verify: "Verify",
    helloAllyUrl: "helloally.ai",
    failedToGenerateOTP: "Failed to generate OTP. Please try again.",
    failedToVerifyOTP: "Failed to verify OTP. Please try again.",
    invalidEmailError: "Please enter a valid email address",
    profileSettings: "Profile settings",
    uploadImage: "Upload image",
    profileImage: "Profile image",
  },
  simulation: {
    duplicatePathwayDescription:
      "Are you sure you want to duplicate this Tracks? This will create a new Tracks with the same configurations.",
    duplicateSimulationDescription:
      "Are you sure you want to duplicate this simulation? This will create a new simulation with the same configurations",
    pathwayDuplicatedSuccessfully: "Tracks duplicated successfully",
    simulationDuplicatedSuccessfully: "Simulation duplicated successfully",
    failedDuplicatePathway: "Failed to duplicate Tracks",
    failedDuplicateSimulation: "Failed to duplicate simulation",
    simulationDeletedSuccessfully: "Simulation deleted successfully",
    failedDeleteSimulation: "Failed to delete simulation",
    failedChangeSimulationStatus: "Failed to change simulation status",
    simulationStatusUpdatedSuccessfully: "Simulation status updated to ",
    failedChangePathwayStatus: "Failed to change Tracks status",
    pathwayStatusUpdatedSuccessfully: "Tracks status updated to ",
    pathwayDeletedSuccessfully: "Tracks deleted successfully",
    failedDeletePathway: "Failed to delete Tracks",
    deletePathway: "Delete Tracks",
    deletePathwayDescription:
      "I understand that deleting this simulation Tracks is permanent and that I will lose all access to users and simulation Tracks analytics.",
    pathway: "Tracks",
    paths: "Tracks",
    createPathway: "Create Tracks",
    videoMaxSizeLabel: "15MB",
    imageMaxSizeLabel: "2MB",
    file: "File",
    addEvent: "Add event",
    unarchive: "Unarchive",
    unarchiveDescription:
      "Are you sure you want to unarchive this simulation? This will make it visible to active simulations.",
    voice: "Voice",
    selectVoice: "Select voice",
    simulationEvents: "Simulation Events",
    createNewEvent: "Create new event",
    selectEventType: "Select the type of event you want to create.",
    createEvent: "Create event",
    editEvent: "Edit event",
    simulationStudio: "Simulation Studio",
    newSimulation: "New simulation",
    newTrack: "New track",
    createYourFirst: "Create your first",
    createYourFirstPathway: "Create your first Tracks",
    simulation: "Simulation",
    unpublish: "Unpublish",
    duplicate: "Duplicate",
    deleteEvent: "Delete event",
    unpublishDescription:
      "Are you sure you want to unpublish this simulation? This will be moved to draft state.",
    newSimulationDescription:
      "Build interactive scenarios for training, education, and practice with our intuitive creation tools.",
    newPathwayDescription: "Search and select simulations to include in this track.",
    createSimulation: "Create simulation",
    createNewSimulation: "Create new simulation",
    publish: "Publish",
    publishing: "Publishing...",
    basicInformation: "Basic Information",
    demographics: "Demographics & Background",
    narrativeContext: "Narrative Context",
    advancedSettings: "Advanced Settings",
    back: "Back",
    next: "Next",
    createdBy: "Created By",
    lastModified: "Last Modified",
    usage: "Usage",
    save: "Save",
    preview: "Preview",
    status: "Status",
    scenario: "Scenario",
    cancel: "Cancel",
    saveAndExit: "Save & Exit",
    discardChanges: "Discard Changes",
    starting: "Starting...",
    close: "Close",
    changes: "changes",
    unsaved: "Unsaved",
    discardDescription: "You have unsaved changes. What would you like to do?",
    archive: "Archive",
    archiveDescription:
      "Are you sure you want to archive this simulation? This will hide it from active simulations but you can restore it later.",
    delete: "Delete",
    deleteDescription: "Permanently delete this",
    deleteConfirmationText:
      "I understand that deleting this simulation is permanent and that I will lose all access to users and simulation analytics",
    deleteForever: "Delete forever",
    title: "Title",
    titlePlaceholder: "Enter title",
    coverImage: "Cover image",
    coverVideo: "Cover video",
    dragDrop: "Drag & drop or",
    choose: "choose",
    pngUploadGuidelines: "a JPEG or PNG file with a",
    mp4UploadGuidelines: "a MP4 or MOV file with a",
    videoUploadGuidelines:
      "resolution of 16:9 aspect ratio,under 15MB, and a duration of up to 15 seconds.",
    resolution: "resolution of 1920x1080 and under 2MB.",
    description: "Description",
    descriptionPlaceholder: "Enter description",
    tags: "Tags",
    learningGoal: "Learning Goal",
    agentGoal: "Agent Goal",
    currentThoughts: "Current Thoughts",
    learningGoalPlaceholder: "What is the primary learning goal?",
    agentGoalPlaceholder: "Describe the agent’s goal for this session.",
    keyLifeEvents: "Key life events",
    keyLifeEventsPlaceholder: "Describe the key life events",
    familyBackground: "Family background and relation",
    familyBackgroundPlaceholder: "Describe family background and relation",
    simulationstudio: "Simulation Studio",
    editSimulation: "Edit Simulation",
    publishTooltipMessage: "Publish becomes available after required details are filled and saved.",
    previewTooltipMessage: "Preview becomes available after required details are filled and saved.",
    simulationPreview: "Simulation Preview",
    eventManagement: "Event Management",
    apply: "Apply",
    noResultFound: "No results found",
    adjustFilter: "Adjust your filters and try again.",
    edit: "Edit",
    editDescription:
      "Are you sure you want to edit this simulation? This will be moved to draft state.",
    startSession: "Start Session",
    autoTermination: "Auto termination",
    triggerEvent: "Trigger event",
    triggerMessage: "Termination dialogue",
    terminationMessagePlaceholder:
      "Enter the message the agent will say before ending the session...",
    triggerEventPlaceholder: "Select an event",
    createPath: "Create Track",
    editPath: "Edit Track",
    addSimulationToPath: "Add simulations to track",
    addSelected: "Add selected",
    addSimulation: "Add Simulation",
    noSimulationsAddedYet: "No simulations added yet",
    minScore: "Minimum score",
    minScoreTooltip: "Minimum score required to complete this simulation",
    addMessage: "Add Message",
    add: "Add",
    editMessage: "Edit Message",
    message: "Message",
    saveSimulation: "Simulation changes saved successfully!",
    noSimulationFound: "No simulations found",
    editPathwayDescription:
      "Are you sure you want to edit this Tracks? This will be moved to draft state.",
    eventCreatedSuccessfully: "Event created successfully",
    eventsDeletedSuccessfully: "Events deleted successfully",
    viewOnly: "View Only",
    viewOnlyTooltip: "The simulation track is currently being used.",
    create: "Create:",
    customFieldLimit: "You can only have 3 custom fields. Remove one to add another.",
    newField: "New field",
  },
  userManagement: {
    organizationCreated: "Organization created successfully",
    organizationUpdated: "Organization updated successfully",
    failedUpdateOrganization: "Failed to update organization",
    addOrganization: "Add organization",
    users: "Users",
    organizations: "Organizations",
    userManagement: "User Management",
    organization: "Organization",
    description: "Description",
    createdOn: "Created on",
    noOfUsers: "No of users",
    user: "User",
    telephonyId: "Telephony ID",
    role: "Role",
    credits: "Credits",
    addedOn: "Added on",
    status: "Status",
    active: "Active",
    suspended: "Suspended",
    addUser: "Add user",
    search: "Search",
    addFilter: "Filter",
    view: "View",
    noOrganization: "No organization found",
    noOrganizationSubtitle:
      "There are no organizations found with selected filters or search query",
    noOrganizationActionLabel: "Add New Organization",
    noUsers: "There are no users found",
    noUsersSubtitle: "There are no users found with selected filters or search query",
    noUsersActionLabel: "Add New User",
    cancel: "Cancel",
    editDetails: "Edit Details",
    changeRole: "Change User Role",
    suspendUserConfirmation: (name: string) =>
      `Are you sure you want to suspend "**${name}**"? They won't be able to log in until reactivated.`,
    removeUserConfirmation: (name: string) =>
      `Are you sure you want to remove "${name}"? This action cannot be undone.`,
    suspendUser: "Suspend User",
    removeUser: "Remove User",
    manageCredit: "Manage Simulation Credits",
    deleteOrganization: "Delete Organization",
    deleteOrganizationConfirmation: (name: string) =>
      `Are you sure you want to remove "${name}"? This action cannot be undone.`,
    select: "Select",
    editOrganization: "Edit Organization",
    confirm: "Confirm",
    selectOrg: "Select Organization",
    grantAccess: "Grant Access",
    grantAccessConfirmation: (name: string) =>
      `Are you sure you want to grant access to "**${name}**"? They will be able to log in and use the system.`,
    consumedCredits: "Consumed credits",
    newCreditLimit: "New credit limit",
    oneCreditInMin: "1 credit = 1 min",
    creditsUsage: "Credits usage",
    currentRoles: "Current roles:",
    textAreaUpperLimit: "Maximum 500 characters allowed",
    maxCharError: (count: number) => `Maximum ${count} characters allowed`,
    changeRoleErrorMessage: "At least one role must be selected",
    creditRequiredError: "Credit details are required",
    creditNotNegativeError: "Credits cannot be negative",
    creditLimitError: "Maximum credit limit is 10,000",
    code: "Code",
    simulations: "Simulations",
    path: "Tracks",
    access: "Access",
    enabled: "Enabled",
    disabled: "Disabled",
    toggleAccess: (title: string) => `Toggle access for ${title}`,
    userRemoved: "User removed successfully",
    logo: "Logo",
    logoDescription: " PNG or JPG files only (240x240 preferred)",
    uploadLogo: "Upload logo",
  },
};
