export const en = {
  common: {
    apply: "Apply",
    search: "Search",
    loading: "Loading...",
    loadMore: "Load more",
    update: "Update",
    create: "Create",
    goBack: "Go Back",
    save: "Save",
    noOptionsAvailable: "No options available",
    noResultsFound: "No results found for",
  },
  accessDenied: {
    title: "This page is not accessible",
    message:
      "You don't have permission to access this page. Please contact your administrator if you believe this is an error.",
  },
  error: {
    apiRequestFailed: "API request failed",
    noRefreshDataReceived: "No refresh data received",
    tokenRefreshFailed: "Token refresh failed",
    userFetchFailed: "User fetch failed",
    permissionsFetchFailed: "Permissions fetch failed",
    authenticationFailed: "Authentication failed",
  },
  auth: {
    hey: "Hey",
    welcomeTo: "Welcome to",
    email: "Email",
    password: "Password",
    login: "Login",
    signup: "Signup",
    forgotPassword: "Forgot Password",
    rememberMe: "Remember Me",
    generatingOTP: "Generating OTP...",
    termsAndConditions: "Terms & Conditions",
    privacyPolicy: "Privacy Policy",
    didNotReceiveTheCode: "Didn't receive the code?",
    signingIn: "Signing in...",
    logout: "Logout",
  },
  simulation: {
    simulationStudio: "Simulation Studio",
    newSimulation: "New simulation",
    createYourFirstSimulation: "Create your first",
    simulation: "Simulation",
    unpublish: "Unpublish",
    unpublishDescription:
      "Are you sure you want to unpublish this simulation? This will be moved to draft state.",
    newSimulationDescription:
      "Build interactive scenarios for training, education, and practice with our intuitive creation tools.",
    createSimulation: "Create simulation",
    createNewSimulation: "Create new simulation",
    publish: "Publish",
    basicInformation: "Basic Information",
    demographics: "Demographics & Background",
    narrativeContext: "Narrative Context",
    eventConfiguration: "Event Configuration",
    back: "Back",
    next: "Next",
    createdBy: "Created By",
    lastModified: "Last Modified",
    usage: "Usage",
    preview: "Preview",
    status: "Status",
    scenario: "Scenario",
    cancel: "Cancel",
    saveAndExit: "Save & Exit",
    discardChanges: "Discard Changes",
    starting: "Starting...",
    close: "Close",
    changes: "changes",
    unsaved: "Unsaved",
    discardDescription:
      "Are you sure you want to discard this simulation? This will be moved to draft state.",
    archive: "Archive",
    archiveDescription:
      "Are you sure you want to archive this simulation? This will hide it from active simulations but you can restore it later.",
    delete: "Delete",
    deleteDescription: "Permanently delete this",
    deleteConfirmationText:
      "I understand that deleting this simulation is permanent and that I will lose all access to users and simulation analytics",
    deleteForever: "Delete forever",
    title: "Title",
    titlePlaceholder: "Enter title",
    upload: "Upload header image",
    dragDrop: "Drag & drop or",
    choose: "choose",
    pngUploadGuidelines: "a JPEG or PNG file with a",
    resolution: "resolution of 1920x1080 and under 2MB.",
    description: "Description",
    descriptionPlaceholder: "Enter description",
    tags: "Tags",
    learningGoal: "Learning Goal",
    currentThoughts: "Current Thoughts",
    learningGoalPlaceholder: "What is the primary learning goal?",
    currentThoughtsPlaceholder: "What are the user's current thoughts on the topic?",
    keyLifeEvents: "Key life events",
    keyLifeEventsPlaceholder: "Describe the key life events",
    familyBackground: "Family background and relation",
    familyBackgroundPlaceholder: "Describe family background and relation",
    simulationstudio: "Simulation Studio",
    editSimulation: "Edit Simulation",
    previewTooltip: "You can preview once all mandatory details are filled and saved.",
    publishTooltip: "You can publish only after all mandatory inputs are filled and saved.",
    simulationPreview: "Simulation Preview",
  },
  userManagement: {
    addOrganization: "Add organization",
    users: "Users",
    organizations: "Organizations",
    userManagement: "User Management",
    organization: "Organization",
    description: "Description",
    createdOn: "Created on",
    noOfUsers: "No of users",
    user: "User",
    telephonyId: "Telephony ID",
    role: "Role",
    credits: "Credits",
    addedOn: "Added on",
    status: "Status",
    active: "Active",
    suspended: "Suspended",
    addUser: "Add user",
    search: "Search",
    addFilter: "Filter",
    delete: "Delete",
    edit: "Edit",
    view: "View",
    noOrganization: "No organization found",
    noOrganizationSubtitle:
      "There are no organizations found with selected filters or search query",
    noOrganizationActionLabel: "Add New Organization",
    noUsers: "There are no users found",
    noUsersSubtitle: "There are no users found with selected filters or search query",
    noUsersActionLabel: "Add New User",
    cancel: "Cancel",
    editDetails: "Edit Details",
    changeRole: "Change User Role",
    suspendUserConfirmation: (name: string) =>
      `Are you sure you want to suspend "**${name}**"? They won't be able to log in until reactivated.`,
    removeUserConfirmation: (name: string) =>
      `Are you sure you want to remove "${name}"? This action cannot be undone.`,
    suspendUser: "Suspend User",
    removeUser: "Remove User",
    addCredit: "Add Simulation Credits",
    deleteOrganization: "Delete Organization",
    deleteOrganizationConfirmation: (name: string) =>
      `Are you sure you want to remove "${name}"? This action cannot be undone.`,
    select: "Select",
    editOrganization: "Edit Organization",
    confirm: "Confirm",
    selectOrg: "Select Organization",
    grantAccess: "Grant Access",
    grantAccessConfirmation: (name: string) =>
      `Are you sure you want to grant access to "**${name}**"? They will be able to log in and use the system.`,
    consumedCredits: "Consumed credits",
    newCreditLimit: "New credit limit",
    oneCreditInMin: "1 credit = 1 min",
    creditsUsage: "Credits usage",
    currentRoles: "Current roles:",
    textAreaUpperLimit: "Maximum 500 characters allowed",
    maxCharError: (count: number) => `Maximum ${count} characters allowed`,
    changeRoleErrorMessage: "At least one role must be selected",
    creditRequiredError: "Credit details are required",
    creditNotNegativeError: "Credits cannot be negative",
    creditLimitError: "Maximum credit limit is 10,000",
    code: "Code",
  },
};
