const getEnvVar = (viteKey: string, nextKey: string): boolean => {
  // Support both Vite (import.meta.env) and Next.js (process.env)
  if (typeof process !== "undefined" && process.env?.[nextKey]) {
    return process.env[nextKey] === "true";
  }
  if (typeof import.meta !== "undefined" && import.meta.env?.[viteKey]) {
    return import.meta.env[viteKey] === "true";
  }
  return false;
};

export const FEATURE_FLAGS_MAP = {
  LANGUAGE_CAPABILITY_FLAG: getEnvVar(
    "VITE_LANGUAGE_CAPABILITY_FLAG",
    "NEXT_PUBLIC_LANGUAGE_CAPABILITY_FLAG",
  ),
  SIMULATION_VOICE_FLAG: getEnvVar(
    "VITE_SIMULATION_VOICE_FLAG",
    "NEXT_PUBLIC_SIMULATION_VOICE_FLAG",
  ),
  ORGANISATION_SETTINGS_FLAG: getEnvVar(
    "VITE_ORGANISATION_SETTINGS_FLAG",
    "NEXT_PUBLIC_ORGANISATION_SETTINGS_FLAG",
  ),
  USER_BADGES_FLAG: getEnvVar("VITE_USER_BADGES_FLAG", "NEXT_PUBLIC_USER_BADGES_FLAG"),
  SIMULATION_CREATOR_FLAG: getEnvVar(
    "VITE_SIMULATION_CREATOR_FLAG",
    "NEXT_PUBLIC_SIMULATION_CREATOR_FLAG",
  ),
  SCRIBE_SETTINGS_FLAG: getEnvVar("VITE_SCRIBE_SETTINGS_FLAG", "NEXT_PUBLIC_SCRIBE_SETTINGS_FLAG"),
  SIMULATION_CASES_FLAG: getEnvVar(
    "VITE_SIMULATION_CASES_FLAG",
    "NEXT_PUBLIC_SIMULATION_CASES_FLAG",
  ),
  MAX_ACTIVE_USERS_POPUP_FLAG: getEnvVar(
    "VITE_MAX_ACTIVE_USERS_POPUP_FLAG",
    "NEXT_PUBLIC_MAX_ACTIVE_USERS_POPUP_FLAG",
  ),
  CHARACTER_LIBRARY_FLAG: getEnvVar(
    "VITE_CHARACTER_LIBRARY_FLAG",
    "NEXT_PUBLIC_CHARACTER_LIBRARY_FLAG",
  ),
  ADDITIONAL_CONFIG_FLAG: getEnvVar(
    "VITE_ADDITIONAL_CONFIG_FLAG",
    "NEXT_PUBLIC_ADDITIONAL_CONFIG_FLAG",
  ),
  SIMULATION_REPORT_FLAG: getEnvVar(
    "VITE_SIMULATION_REPORT_FLAG",
    "NEXT_PUBLIC_SIMULATION_REPORT_FLAG",
  ),
  SUMMARY_TABS_FLAG: getEnvVar("VITE_SUMMARY_TABS_FLAG", "NEXT_PUBLIC_SUMMARY_TABS_FLAG"),
};
