import { FEATURE_FLAGS_MAP } from "@ally-ui-mono/ui-shared";
import {
  CallDetails,
  SessionSummary,
  Flow,
  KeyConcerns,
  ObjectiveObservations,
  SubjectiveObservations,
  Assessment,
  DominantFeelings,
  IssuesWorkedOn,
  TherapeuticTechniques,
  ReferralsProvided,
  HomeworkRecommended,
  PlansForNextCall,
  Tags,
  Metrics,
  Intake,
  OngoingRisks,
} from "@assets/icons";
import { SummaryFieldKey } from "@types";

import { FieldType, SectionType, SummaryField, SummarySectionKey } from "./types";

export const summaryTabs = [
  {
    labelKey: "summary.tabs.returnToSelf",
    value: SectionType.BoxBreathing,
  },
  {
    labelKey: "summary.tabs.sessionSummary",
    value: SectionType.SessionSummary,
  },
];

export const summarySections = [
  {
    icon: {
      icon: CallDetails,
      alt: "features-and-demographics",
    },
    key: SummarySectionKey.FeaturesAndDemographics,
    titleKey: "summary.sections.featuresAndDemographics",
  },
  {
    icon: {
      icon: SessionSummary,
      alt: "session-summary",
    },
    key: SummarySectionKey.SessionSummary,
    titleKey: "summary.sections.sessionSummary",
  },
  {
    icon: {
      icon: Flow,
      alt: "flow",
    },
    key: SummarySectionKey.Flow,
    titleKey: "summary.sections.flow",
  },
  {
    icon: {
      icon: KeyConcerns,
      alt: "key-concerns",
    },
    key: SummarySectionKey.KeyConcerns,
    titleKey: "summary.sections.keyConcerns",
  },
  {
    icon: {
      icon: ObjectiveObservations,
      alt: "objective-observations",
    },
    key: SummarySectionKey.ObjectiveObservations,
    titleKey: "summary.sections.objectiveObservations",
  },
  {
    icon: {
      icon: SubjectiveObservations,
      alt: "subjective-observations",
    },
    key: SummarySectionKey.SubjectiveObservations,
    titleKey: "summary.sections.subjectiveObservations",
  },
  {
    icon: {
      icon: Assessment,
      alt: "assessment",
    },
    key: SummarySectionKey.Assessment,
    titleKey: "summary.sections.assessment",
  },
  {
    icon: {
      icon: DominantFeelings,
      alt: "dominant-feelings",
    },
    key: SummarySectionKey.DominantFeelings,
    titleKey: "summary.sections.dominantFeelings",
  },
  {
    icon: {
      icon: IssuesWorkedOn,
      alt: "issues-worked-on",
    },
    key: SummarySectionKey.IssuesWorkedOn,
    titleKey: "summary.sections.issuesWorkedOn",
  },
  {
    icon: {
      icon: TherapeuticTechniques,
      alt: "key-therapeutic-techniques",
    },
    key: SummarySectionKey.KeyTherapeuticTechniques,
    titleKey: "summary.sections.keyTherapeuticTechniques",
  },
  {
    icon: {
      icon: ReferralsProvided,
      alt: "referrals-provided",
    },
    key: SummarySectionKey.ReferralsProvided,
    titleKey: "summary.sections.referralsProvided",
  },
  {
    icon: {
      icon: HomeworkRecommended,
      alt: "homework-recommended",
    },
    key: SummarySectionKey.HomeworkRecommended,
    titleKey: "summary.sections.homeworkRecommended",
  },
  {
    icon: {
      icon: PlansForNextCall,
      alt: "plans-for-next-call",
    },
    key: SummarySectionKey.PlansForNextCall,
    titleKey: "summary.sections.plansForNextCall",
  },
  {
    icon: {
      icon: Tags,
      alt: "tags",
    },
    key: SummarySectionKey.Tags,
    titleKey: "summary.sections.tags",
  },
  {
    icon: {
      icon: Metrics,
      alt: "metrics",
    },
    key: SummarySectionKey.Metrics,
    titleKey: "summary.sections.metrics",
  },
  ...(FEATURE_FLAGS_MAP.SCRIBE_SETTINGS_FLAG
    ? [
        {
          icon: {
            icon: Intake,
            alt: "intake",
          },
          key: SummarySectionKey.Intake,
          title: "Intake",
        },
        {
          icon: {
            icon: OngoingRisks,
            alt: "ongoing-risks",
          },
          key: SummarySectionKey.OngoingRisks,
          title: "Ongoing Risks",
        },
      ]
    : []),
];

export const summaryFields: SummaryField[] = [
  // Features and Demographics section
  {
    isEditable: false,
    key: SummaryFieldKey.CallId,
    label: "Call ID",
    labelKey: "summary.fields.callId",
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Text,
  },
  {
    isEditable: false,
    key: SummaryFieldKey.CallDuration,
    label: "Call Duration",
    labelKey: "summary.fields.callDuration",
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Text,
  },
  {
    isEditable: false,
    key: SummaryFieldKey.CallDate,
    label: "Call Date",
    labelKey: "summary.fields.callDate",
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Text,
  },
  {
    isEditable: false,
    key: SummaryFieldKey.CallTime,
    label: "Call time",
    labelKey: "summary.fields.callTime",
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Text,
  },
  {
    isEditable: true,
    key: SummaryFieldKey.NewCallFollowUp,
    label: "New Call Follow Up",
    labelKey: "summary.fields.newCallFollowUp",
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Text,
  },
  {
    isEditable: true,
    key: SummaryFieldKey.Counsellor,
    label: "Counsellor",
    labelKey: "summary.fields.counsellor",
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Text,
  },
  {
    isEditable: true,
    key: SummaryFieldKey.CallQuality,
    label: "Call Quality",
    labelKey: "summary.fields.callQuality",
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Text,
  },
  {
    isEditable: false,
    key: SummaryFieldKey.ClientId,
    label: "Caller ID",
    labelKey: "summary.fields.callerId",
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Text,
  },
  {
    isEditable: false,
    key: SummaryFieldKey.CounsellorName,
    label: "Counsellor Name",
    labelKey: "summary.fields.counsellorName",
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Text,
  },
  {
    isEditable: false,
    key: SummaryFieldKey.CallType,
    label: "Caller type",
    labelKey: "summary.fields.callerType",
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Text,
  },
  {
    isEditable: true,
    key: SummaryFieldKey.Age,
    label: "Age",
    labelKey: "summary.fields.age",
    options: ["0-5", "6-12", "13-17", "18-24", "25-34", "35-44", "45-54", "55-64", "65+"],
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Dropdown,
  },
  {
    isEditable: true,
    key: SummaryFieldKey.Gender,
    label: "Gender",
    labelKey: "summary.fields.gender",
    options: ["Male", "Female", "Non-binary", "Client Prefers Not to Say"],
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Dropdown,
  },
  {
    isEditable: true,
    key: SummaryFieldKey.Profession,
    label: "Profession",
    labelKey: "summary.fields.profession",
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Text,
  },
  {
    isEditable: true,
    key: SummaryFieldKey.RelationshipStatus,
    label: "Relationship status",
    labelKey: "summary.fields.relationshipStatus",
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Text,
  },
  {
    isEditable: false,
    key: SummaryFieldKey.Languages,
    label: "Languages",
    labelKey: "summary.fields.languages",
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Text,
  },
  {
    isEditable: true,
    key: SummaryFieldKey.Location,
    label: "Location",
    labelKey: "summary.fields.location",
    options: [],
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Dropdown,
  },
  {
    isEditable: true,
    key: SummaryFieldKey.CodeOfConcern,
    label: "Concern code",
    labelKey: "summary.fields.concernCode",
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Text,
  },
  // Other fields
  {
    isEditable: true,
    isEnhanceable: true,
    key: SummaryFieldKey.SessionSummary,
    label: "Session Summary",
    labelKey: "summary.fields.sessionSummary",
    placeholderKey: "summary.placeholders.sessionSummary",
    sectionKey: SummarySectionKey.SessionSummary,
    type: FieldType.Multiline,
  },
  {
    isEditable: true,
    isEnhanceable: true,
    key: SummaryFieldKey.CounselingProcessFlow,
    label: "Flow",
    labelKey: "summary.fields.flow",
    placeholderKey: "summary.placeholders.flow",
    sectionKey: SummarySectionKey.Flow,
    type: FieldType.Multiline,
  },
  {
    isEditable: true,
    isEnhanceable: true,
    key: SummaryFieldKey.KeyConcerns,
    label: "Key concerns",
    labelKey: "summary.fields.keyConcerns",
    placeholderKey: "summary.placeholders.keyConcerns",
    sectionKey: SummarySectionKey.KeyConcerns,
    type: FieldType.Multiline,
  },
  {
    isEditable: true,
    isEnhanceable: true,
    key: SummaryFieldKey.ObjectiveObservations,
    label: "Objective Observations",
    labelKey: "summary.fields.objectiveObservations",
    placeholderKey: "summary.placeholders.objectiveObservations",
    sectionKey: SummarySectionKey.ObjectiveObservations,
    type: FieldType.Multiline,
  },
  {
    isEditable: true,
    isEnhanceable: true,
    key: SummaryFieldKey.SubjectiveObservations,
    label: "Subjective Observations",
    labelKey: "summary.fields.subjectiveObservations",
    placeholderKey: "summary.placeholders.subjectiveObservations",
    sectionKey: SummarySectionKey.SubjectiveObservations,
    type: FieldType.Multiline,
  },
  {
    isEditable: true,
    isEnhanceable: true,
    key: SummaryFieldKey.Assessment,
    label: "Assessment",
    labelKey: "summary.fields.assessment",
    placeholderKey: "summary.placeholders.assessment",
    sectionKey: SummarySectionKey.Assessment,
    type: FieldType.Multiline,
  },
  {
    isEditable: true,
    isEnhanceable: true,
    key: SummaryFieldKey.DominantFeelings,
    label: "Dominant Feelings",
    labelKey: "summary.fields.dominantFeelings",
    placeholderKey: "summary.placeholders.dominantFeelings",
    sectionKey: SummarySectionKey.DominantFeelings,
    type: FieldType.Multiline,
  },
  {
    isEditable: true,
    isEnhanceable: true,
    key: SummaryFieldKey.IssuesWorkedOn,
    label: "Issues Worked On",
    labelKey: "summary.fields.issuesWorkedOn",
    placeholderKey: "summary.placeholders.issuesWorkedOn",
    sectionKey: SummarySectionKey.IssuesWorkedOn,
    type: FieldType.Multiline,
  },
  {
    isEditable: true,
    isEnhanceable: true,
    key: SummaryFieldKey.KeyTherapeuticTechniques,
    label: "Key Therapeutic Techniques",
    labelKey: "summary.fields.keyTherapeuticTechniques",
    placeholderKey: "summary.placeholders.keyTherapeuticTechniques",
    sectionKey: SummarySectionKey.KeyTherapeuticTechniques,
    type: FieldType.Multiline,
  },
  {
    isEditable: true,
    isEnhanceable: true,
    key: SummaryFieldKey.ReferralsProvided,
    label: "Referrals Provided",
    labelKey: "summary.fields.referralsProvided",
    placeholderKey: "summary.placeholders.referralsProvided",
    sectionKey: SummarySectionKey.ReferralsProvided,
    type: FieldType.Multiline,
  },
  {
    isEditable: true,
    isEnhanceable: true,
    key: SummaryFieldKey.Homework,
    label: "Homework Recommended",
    labelKey: "summary.fields.homeworkRecommended",
    placeholderKey: "summary.placeholders.homework",
    sectionKey: SummarySectionKey.HomeworkRecommended,
    type: FieldType.Multiline,
  },
  {
    isEditable: true,
    isEnhanceable: true,
    key: SummaryFieldKey.PlanForNextCall,
    label: "Plans for Next Call",
    labelKey: "summary.fields.plansForNextCall",
    placeholderKey: "summary.placeholders.planForNextCall",
    sectionKey: SummarySectionKey.PlansForNextCall,
    type: FieldType.Multiline,
  },
  {
    isEditable: true,
    isEnhanceable: false,
    key: SummaryFieldKey.Tags,
    label: "Tags",
    labelKey: "summary.fields.tags",
    placeholderKey: "summary.placeholders.tags",
    sectionKey: SummarySectionKey.Tags,
    type: FieldType.Multiline,
  },

  // Metrics section
  {
    isEditable: false,
    key: SummaryFieldKey.ListeningShare,
    label: "Listening Ratio",
    labelKey: "summary.fields.listeningRatio",
    sectionKey: SummarySectionKey.Metrics,
    type: FieldType.Text,
  },
  {
    isEditable: false,
    key: SummaryFieldKey.ReflectiveQuestionsAsked,
    label: "No of Reflective Questions asked",
    labelKey: "summary.fields.reflectiveQuestions",
    sectionKey: SummarySectionKey.Metrics,
    type: FieldType.Text,
  },
  {
    isEditable: false,
    key: SummaryFieldKey.EmotionalLift,
    label: "Emotions Lift",
    labelKey: "summary.fields.emotionsLift",
    sectionKey: SummarySectionKey.Metrics,
    type: FieldType.Text,
  },
  {
    isEditable: false,
    key: SummaryFieldKey.OpenEndedQuestionsAsked,
    label: "No of Open Ended Questions asked",
    labelKey: "summary.fields.openEndedQuestions",
    sectionKey: SummarySectionKey.Metrics,
    type: FieldType.Text,
  },
  // Intake section
  ...(FEATURE_FLAGS_MAP.SCRIBE_SETTINGS_FLAG
    ? [
        {
          isEditable: true,
          key: SummaryFieldKey.IntakeNotes,
          label: "Intake Notes",
          sectionKey: SummarySectionKey.Intake,
          type: FieldType.Text,
          placeholderKey: "summary.placeholders.addNote",
        },
        {
          isEditable: true,
          key: SummaryFieldKey.RiskSelfHarm,
          label: "Risk, Self Harm",
          sectionKey: SummarySectionKey.Intake,
          type: FieldType.Dropdown,
          options: ["Yes", "No"],
          placeholderKey: "summary.placeholders.select",
        },
        {
          isEditable: true,
          key: SummaryFieldKey.RiskSelfHarmNotes,
          label: "Risk, Self Harm Notes",
          sectionKey: SummarySectionKey.Intake,
          type: FieldType.Text,
          placeholderKey: "summary.placeholders.addNote",
        },
        {
          isEditable: true,
          key: SummaryFieldKey.RiskSuicidalThoughts,
          label: "Risk, Suicidal Thoughts",
          sectionKey: SummarySectionKey.Intake,
          type: FieldType.Dropdown,
          options: ["Yes", "No"],
          placeholderKey: "summary.placeholders.select",
        },
        {
          isEditable: true,
          key: SummaryFieldKey.RiskSuicidalThoughtsNotes,
          label: "Risk, Suicidal Thoughts Notes",
          sectionKey: SummarySectionKey.Intake,
          type: FieldType.Text,
          placeholderKey: "summary.placeholders.addNote",
        },
        {
          isEditable: true,
          key: SummaryFieldKey.RiskSuicidalPlan,
          label: "Risk, Suicidal Plan",
          sectionKey: SummarySectionKey.Intake,
          type: FieldType.Dropdown,
          options: ["Yes", "No"],
          placeholderKey: "summary.placeholders.select",
        },
        {
          isEditable: true,
          key: SummaryFieldKey.RiskSuicidalAction,
          label: "Risk, Suicidal Action",
          sectionKey: SummarySectionKey.Intake,
          type: FieldType.Dropdown,
          options: ["Yes", "No"],
          placeholderKey: "summary.placeholders.select",
        },
        {
          isEditable: true,
          key: SummaryFieldKey.RiskRunningAway,
          label: "Risk, Running Away",
          sectionKey: SummarySectionKey.Intake,
          type: FieldType.Dropdown,
          options: ["Yes", "No"],
          placeholderKey: "summary.placeholders.select",
        },
        {
          isEditable: true,
          key: SummaryFieldKey.RiskRunningAwayNotes,
          label: "Risk, Running Away Notes",
          sectionKey: SummarySectionKey.Intake,
          type: FieldType.Text,
          placeholderKey: "summary.placeholders.addNote",
        },
        {
          isEditable: true,
          key: SummaryFieldKey.TraumaPhysicalAbuse,
          label: "Trauma, Physical Abuse",
          sectionKey: SummarySectionKey.Intake,
          type: FieldType.Dropdown,
          options: ["Yes", "No"],
          placeholderKey: "summary.placeholders.select",
        },
        {
          isEditable: true,
          key: SummaryFieldKey.TraumaSexualAbuse,
          label: "Trauma, Sexual Abuse",
          sectionKey: SummarySectionKey.Intake,
          type: FieldType.Dropdown,
          options: ["Yes", "No"],
          placeholderKey: "summary.placeholders.select",
        },
        {
          isEditable: true,
          key: SummaryFieldKey.TraumaVerbalAbuse,
          label: "Trauma, Verbal Abuse",
          sectionKey: SummarySectionKey.Intake,
          type: FieldType.Dropdown,
          options: ["Yes", "No"],
          placeholderKey: "summary.placeholders.select",
        },
        {
          isEditable: true,
          key: SummaryFieldKey.TraumaNeglect,
          label: "Trauma, Neglect",
          sectionKey: SummarySectionKey.Intake,
          type: FieldType.Dropdown,
          options: ["Yes", "No"],
          placeholderKey: "summary.placeholders.select",
        },
        {
          isEditable: true,
          key: SummaryFieldKey.TraumaSeparationFromCaregiverParent,
          label: "Trauma, Separation from Caregiver/Parent",
          sectionKey: SummarySectionKey.Intake,
          type: FieldType.Dropdown,
          options: ["Yes", "No"],
          placeholderKey: "summary.placeholders.select",
        },
        {
          isEditable: true,
          key: SummaryFieldKey.TraumaWitnessedDomesticViolence,
          label: "Trauma, Witnessed Domestic Violence",
          sectionKey: SummarySectionKey.Intake,
          type: FieldType.Dropdown,
          options: ["Yes", "No"],
          placeholderKey: "summary.placeholders.select",
        },
        {
          isEditable: true,
          key: SummaryFieldKey.TraumaNotes,
          label: "Trauma Notes",
          sectionKey: SummarySectionKey.Intake,
          type: FieldType.Text,
          placeholderKey: "summary.placeholders.addNote",
        },
        {
          isEditable: true,
          key: SummaryFieldKey.AssessmentPsychologicalDiagnosis,
          label: "Assessment, Psychological Diagnosis",
          sectionKey: SummarySectionKey.Intake,
          type: FieldType.Dropdown,
          options: ["Yes", "No"],
          placeholderKey: "summary.placeholders.select",
        },
        {
          isEditable: true,
          key: SummaryFieldKey.AssessmentPsychologicalDiagnosisNotes,
          label: "Assessment, Psychological Diagnosis Notes",
          sectionKey: SummarySectionKey.Intake,
          type: FieldType.Text,
          placeholderKey: "summary.placeholders.addNote",
        },
        {
          isEditable: true,
          key: SummaryFieldKey.AssessmentUseOfPsychotropicMedications,
          label: "Assessment, Use of Psychotropic Medications",
          sectionKey: SummarySectionKey.Intake,
          type: FieldType.Dropdown,
          options: ["Yes", "No"],
          placeholderKey: "summary.placeholders.select",
        },
        {
          isEditable: true,
          key: SummaryFieldKey.AssessmentUseOfPsychotropicMedicationsNotes,
          label: "Assessment, Use of Psychotropic Medications Notes",
          sectionKey: SummarySectionKey.Intake,
          type: FieldType.Text,
          placeholderKey: "summary.placeholders.addNote",
        },
        {
          isEditable: true,
          key: SummaryFieldKey.AssessmentHallucinations,
          label: "Assessment, Hallucinations",
          sectionKey: SummarySectionKey.Intake,
          type: FieldType.Dropdown,
          options: ["Yes", "No"],
          placeholderKey: "summary.placeholders.select",
        },
        {
          isEditable: true,
          key: SummaryFieldKey.AssessmentHallucinationsNotes,
          label: "Assessment, Hallucinations Notes",
          sectionKey: SummarySectionKey.Intake,
          type: FieldType.Text,
          placeholderKey: "summary.placeholders.addNote",
        },
        {
          isEditable: true,
          key: SummaryFieldKey.AssessmentAffect,
          label: "Assessment, Affect",
          sectionKey: SummarySectionKey.Intake,
          type: FieldType.Dropdown,
          options: ["Congruent", "Incongruent", "Flat", "Blunted"],
          placeholderKey: "summary.placeholders.select",
        },
        {
          isEditable: true,
          key: SummaryFieldKey.AssessmentSpeech,
          label: "Assessment, Speech",
          sectionKey: SummarySectionKey.Intake,
          type: FieldType.Dropdown,
          options: ["Clear & Coherent", "Sluttering", "Fast", "Slow", "Difficult to Understand"],
          placeholderKey: "summary.placeholders.select",
        },
        // Ongoing Risks section
        {
          isEditable: true,
          key: SummaryFieldKey.OngoingRiskSelfHarm,
          label: "Ongoing Risk, Self Harm",
          sectionKey: SummarySectionKey.OngoingRisks,
          type: FieldType.Dropdown,
          options: ["Yes", "No"],
          placeholderKey: "summary.placeholders.select",
        },
        {
          isEditable: true,
          key: SummaryFieldKey.OngoingRiskSelfHarmNotes,
          label: "Ongoing Risk, Self Harm Notes",
          sectionKey: SummarySectionKey.OngoingRisks,
          type: FieldType.Text,
          placeholderKey: "summary.placeholders.addNote",
        },
        {
          isEditable: true,
          key: SummaryFieldKey.OngoingRiskSuicidalThoughts,
          label: "Ongoing Risk, Suicidal Thoughts",
          sectionKey: SummarySectionKey.OngoingRisks,
          type: FieldType.Dropdown,
          options: ["Yes", "No"],
          placeholderKey: "summary.placeholders.select",
        },
        {
          isEditable: true,
          key: SummaryFieldKey.OngoingRiskSuicidalPlan,
          label: "Ongoing Risk, Suicidal Plan",
          sectionKey: SummarySectionKey.OngoingRisks,
          type: FieldType.Dropdown,
          options: ["Yes", "No"],
          placeholderKey: "summary.placeholders.select",
        },
        {
          isEditable: true,
          key: SummaryFieldKey.OngoingRiskSuicidalAction,
          label: "Ongoing Risk, Suicidal Action",
          sectionKey: SummarySectionKey.OngoingRisks,
          type: FieldType.Dropdown,
          options: ["Yes", "No"],
          placeholderKey: "summary.placeholders.select",
        },
        {
          isEditable: true,
          key: SummaryFieldKey.OngoingRiskSuicidalThoughtsNotes,
          label: "Ongoing Risk, Suicidal Thoughts Notes",
          sectionKey: SummarySectionKey.OngoingRisks,
          type: FieldType.Text,
          placeholderKey: "summary.placeholders.addNote",
        },
      ]
    : []),
];

export const labelShownSections = [
  SummarySectionKey.FeaturesAndDemographics,
  SummarySectionKey.Metrics,
];

export const postCallSectionOrder = [SectionType.BoxBreathing, SectionType.SessionSummary];

export const SectionQueryKey = "section";

export const SourceQueryKey = "source";

export const DeeplinkSourceValue = "deeplink";

export const PostCallProcessingMessages = [
  "Generating transcription",
  "Deleting audio",
  "Segregating utterances",
  "Understanding conversation",
  "Charting flow",
  "Extracting key points",
  "Identifying themes",
  "Analysing",
  "Generating summary",
  "Enriching summary",
  "Validating summary",
];

// TODO: Decide on  a format for const files
// Start index of sumamry message that should be loopedß
export const SUMMARY_GENERATION_START_INDEX = 8;
