import { TFunction } from "i18next";

import {
  CallDetails,
  SessionSummary,
  Flow,
  KeyConcerns,
  ObjectiveObservations,
  SubjectiveObservations,
  Assessment,
  DominantFeelings,
  IssuesWorkedOn,
  TherapeuticTechniques,
  ReferralsProvided,
  HomeworkRecommended,
  PlansForNextCall,
  Tags,
  Metrics,
  Intake,
  OngoingRisks,
} from "@assets/icons";
import { SummaryFieldKey } from "@types";

import { FieldType, SectionType, SummaryField, SummarySectionKey } from "./types";

// ─── Factory functions (translated) ──────────────────────────────────────────

export const getSummaryTabs = (t: TFunction) => [
  { label: t("summary.tabs.returnToSelf"), value: SectionType.BoxBreathing },
  { label: t("summary.tabs.sessionSummary"), value: SectionType.SessionSummary },
  { label: t("summary.tabs.transcript"), value: SectionType.Transcript },
];

export const getSummarySections = (t: TFunction) => [
  {
    icon: { icon: CallDetails, alt: "features-and-demographics" },
    key: SummarySectionKey.FeaturesAndDemographics,
    title: t("summary.sections.featuresAndDemographics"),
  },
  {
    icon: { icon: SessionSummary, alt: "session-summary" },
    key: SummarySectionKey.SessionSummary,
    title: t("summary.sections.sessionSummary"),
  },
  {
    icon: { icon: Flow, alt: "flow" },
    key: SummarySectionKey.Flow,
    title: t("summary.sections.flow"),
  },
  {
    icon: { icon: KeyConcerns, alt: "key-concerns" },
    key: SummarySectionKey.KeyConcerns,
    title: t("summary.sections.keyConcerns"),
  },
  {
    icon: { icon: ObjectiveObservations, alt: "objective-observations" },
    key: SummarySectionKey.ObjectiveObservations,
    title: t("summary.sections.objectiveObservations"),
  },
  {
    icon: { icon: SubjectiveObservations, alt: "subjective-observations" },
    key: SummarySectionKey.SubjectiveObservations,
    title: t("summary.sections.subjectiveObservations"),
  },
  {
    icon: { icon: Assessment, alt: "assessment" },
    key: SummarySectionKey.Assessment,
    title: t("summary.sections.assessment"),
  },
  {
    icon: { icon: DominantFeelings, alt: "dominant-feelings" },
    key: SummarySectionKey.DominantFeelings,
    title: t("summary.sections.dominantFeelings"),
  },
  {
    icon: { icon: IssuesWorkedOn, alt: "issues-worked-on" },
    key: SummarySectionKey.IssuesWorkedOn,
    title: t("summary.sections.issuesWorkedOn"),
  },
  {
    icon: { icon: TherapeuticTechniques, alt: "key-therapeutic-techniques" },
    key: SummarySectionKey.KeyTherapeuticTechniques,
    title: t("summary.sections.keyTherapeuticTechniques"),
  },
  {
    icon: { icon: ReferralsProvided, alt: "referrals-provided" },
    key: SummarySectionKey.ReferralsProvided,
    title: t("summary.sections.referralsProvided"),
  },
  {
    icon: { icon: HomeworkRecommended, alt: "homework-recommended" },
    key: SummarySectionKey.HomeworkRecommended,
    title: t("summary.sections.homeworkRecommended"),
  },
  {
    icon: { icon: PlansForNextCall, alt: "plans-for-next-call" },
    key: SummarySectionKey.PlansForNextCall,
    title: t("summary.sections.plansForNextCall"),
  },
  {
    icon: { icon: Tags, alt: "tags" },
    key: SummarySectionKey.Tags,
    title: t("summary.sections.tags"),
  },
  {
    icon: { icon: Metrics, alt: "metrics" },
    key: SummarySectionKey.Metrics,
    title: t("summary.sections.metrics"),
  },
  {
    icon: { icon: Intake, alt: "intake" },
    key: SummarySectionKey.Intake,
    title: t("summary.sections.intake"),
  },
  {
    icon: { icon: OngoingRisks, alt: "ongoing-risks" },
    key: SummarySectionKey.OngoingRisks,
    title: t("summary.sections.ongoingRisks"),
  },
];

export const getSummaryFields = (t: TFunction): SummaryField[] => [
  // Features and Demographics
  {
    isEditable: false,
    key: SummaryFieldKey.CallId,
    label: t("summary.fields.callId"),
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Text,
  },
  {
    isEditable: false,
    key: SummaryFieldKey.CallDuration,
    label: t("summary.fields.callDuration"),
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Text,
  },
  {
    isEditable: false,
    key: SummaryFieldKey.CallDate,
    label: t("summary.fields.callDate"),
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Text,
  },
  {
    isEditable: false,
    key: SummaryFieldKey.CallTime,
    label: t("summary.fields.callTime"),
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Text,
  },
  {
    isEditable: true,
    key: SummaryFieldKey.NewCallFollowUp,
    label: t("summary.fields.newCallFollowUp"),
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Text,
  },
  {
    isEditable: true,
    key: SummaryFieldKey.Counsellor,
    label: t("summary.fields.counsellor"),
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Text,
  },
  {
    isEditable: true,
    key: SummaryFieldKey.CallQuality,
    label: t("summary.fields.callQuality"),
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Text,
  },
  {
    isEditable: false,
    key: SummaryFieldKey.ClientId,
    label: t("summary.fields.callerId"),
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Text,
  },
  {
    isEditable: false,
    key: SummaryFieldKey.CounsellorName,
    label: t("summary.fields.counsellorName"),
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Text,
  },
  {
    isEditable: false,
    key: SummaryFieldKey.CallType,
    label: t("summary.fields.callerType"),
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Text,
  },
  {
    isEditable: true,
    key: SummaryFieldKey.Age,
    label: t("summary.fields.age"),
    options: ["0-5", "6-12", "13-17", "18-24", "25-34", "35-44", "45-54", "55-64", "65+"],
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Dropdown,
  },
  {
    isEditable: true,
    key: SummaryFieldKey.Gender,
    label: t("summary.fields.gender"),
    options: ["Male", "Female", "Non-binary", "Client Prefers Not to Say"],
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Dropdown,
  },
  {
    isEditable: true,
    key: SummaryFieldKey.Profession,
    label: t("summary.fields.profession"),
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Text,
  },
  {
    isEditable: true,
    key: SummaryFieldKey.RelationshipStatus,
    label: t("summary.fields.relationshipStatus"),
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Text,
  },
  {
    isEditable: false,
    key: SummaryFieldKey.Languages,
    label: t("summary.fields.languages"),
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Text,
  },
  {
    isEditable: true,
    key: SummaryFieldKey.Location,
    label: t("summary.fields.location"),
    options: [],
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Dropdown,
  },
  {
    isEditable: true,
    key: SummaryFieldKey.CodeOfConcern,
    label: t("summary.fields.concernCode"),
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Text,
  },
  // Narrative sections
  {
    isEditable: true,
    isEnhanceable: true,
    key: SummaryFieldKey.SessionSummary,
    label: t("summary.fields.sessionSummary"),
    placeholder: t("summary.placeholders.sessionSummary"),
    sectionKey: SummarySectionKey.SessionSummary,
    type: FieldType.Multiline,
  },
  {
    isEditable: true,
    isEnhanceable: true,
    key: SummaryFieldKey.CounselingProcessFlow,
    label: t("summary.fields.flow"),
    placeholder: t("summary.placeholders.flow"),
    sectionKey: SummarySectionKey.Flow,
    type: FieldType.Multiline,
  },
  {
    isEditable: true,
    isEnhanceable: true,
    key: SummaryFieldKey.KeyConcerns,
    label: t("summary.fields.keyConcerns"),
    placeholder: t("summary.placeholders.keyConcerns"),
    sectionKey: SummarySectionKey.KeyConcerns,
    type: FieldType.Multiline,
  },
  {
    isEditable: true,
    isEnhanceable: true,
    key: SummaryFieldKey.ObjectiveObservations,
    label: t("summary.fields.objectiveObservations"),
    placeholder: t("summary.placeholders.objectiveObservations"),
    sectionKey: SummarySectionKey.ObjectiveObservations,
    type: FieldType.Multiline,
  },
  {
    isEditable: true,
    isEnhanceable: true,
    key: SummaryFieldKey.SubjectiveObservations,
    label: t("summary.fields.subjectiveObservations"),
    placeholder: t("summary.placeholders.subjectiveObservations"),
    sectionKey: SummarySectionKey.SubjectiveObservations,
    type: FieldType.Multiline,
  },
  {
    isEditable: true,
    isEnhanceable: true,
    key: SummaryFieldKey.Assessment,
    label: t("summary.fields.assessment"),
    placeholder: t("summary.placeholders.assessment"),
    sectionKey: SummarySectionKey.Assessment,
    type: FieldType.Multiline,
  },
  {
    isEditable: true,
    isEnhanceable: true,
    key: SummaryFieldKey.DominantFeelings,
    label: t("summary.fields.dominantFeelings"),
    placeholder: t("summary.placeholders.dominantFeelings"),
    sectionKey: SummarySectionKey.DominantFeelings,
    type: FieldType.Multiline,
  },
  {
    isEditable: true,
    isEnhanceable: true,
    key: SummaryFieldKey.IssuesWorkedOn,
    label: t("summary.fields.issuesWorkedOn"),
    placeholder: t("summary.placeholders.issuesWorkedOn"),
    sectionKey: SummarySectionKey.IssuesWorkedOn,
    type: FieldType.Multiline,
  },
  {
    isEditable: true,
    isEnhanceable: true,
    key: SummaryFieldKey.KeyTherapeuticTechniques,
    label: t("summary.fields.keyTherapeuticTechniques"),
    placeholder: t("summary.placeholders.keyTherapeuticTechniques"),
    sectionKey: SummarySectionKey.KeyTherapeuticTechniques,
    type: FieldType.Multiline,
  },
  {
    isEditable: true,
    isEnhanceable: true,
    key: SummaryFieldKey.ReferralsProvided,
    label: t("summary.fields.referralsProvided"),
    placeholder: t("summary.placeholders.referralsProvided"),
    sectionKey: SummarySectionKey.ReferralsProvided,
    type: FieldType.Multiline,
  },
  {
    isEditable: true,
    isEnhanceable: true,
    key: SummaryFieldKey.Homework,
    label: t("summary.fields.homeworkRecommended"),
    placeholder: t("summary.placeholders.homework"),
    sectionKey: SummarySectionKey.HomeworkRecommended,
    type: FieldType.Multiline,
  },
  {
    isEditable: true,
    isEnhanceable: true,
    key: SummaryFieldKey.PlanForNextCall,
    label: t("summary.fields.plansForNextCall"),
    placeholder: t("summary.placeholders.planForNextCall"),
    sectionKey: SummarySectionKey.PlansForNextCall,
    type: FieldType.Multiline,
  },
  {
    isEditable: true,
    isEnhanceable: false,
    key: SummaryFieldKey.Tags,
    label: t("summary.fields.tags"),
    placeholder: t("summary.placeholders.tags"),
    sectionKey: SummarySectionKey.Tags,
    type: FieldType.Multiline,
  },
  // Metrics
  {
    isEditable: false,
    key: SummaryFieldKey.ListeningShare,
    label: t("summary.fields.listeningRatio"),
    sectionKey: SummarySectionKey.Metrics,
    type: FieldType.Text,
  },
  {
    isEditable: false,
    key: SummaryFieldKey.ReflectiveQuestionsAsked,
    label: t("summary.fields.reflectiveQuestions"),
    sectionKey: SummarySectionKey.Metrics,
    type: FieldType.Text,
  },
  {
    isEditable: false,
    key: SummaryFieldKey.EmotionalLift,
    label: t("summary.fields.emotionsLift"),
    sectionKey: SummarySectionKey.Metrics,
    type: FieldType.Text,
  },
  {
    isEditable: false,
    key: SummaryFieldKey.OpenEndedQuestionsAsked,
    label: t("summary.fields.openEndedQuestions"),
    sectionKey: SummarySectionKey.Metrics,
    type: FieldType.Text,
  },
  // Intake
  {
    isEditable: true,
    key: SummaryFieldKey.IntakeNotes,
    label: t("summary.fields.intakeNotes"),
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Text,
    placeholder: t("summary.placeholders.addNote"),
  },
  {
    isEditable: true,
    key: SummaryFieldKey.RiskSelfHarm,
    label: t("summary.fields.riskSelfHarm"),
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Dropdown,
    options: ["Yes", "No"],
    placeholder: t("summary.placeholders.select"),
  },
  {
    isEditable: true,
    key: SummaryFieldKey.RiskSelfHarmNotes,
    label: t("summary.fields.riskSelfHarmNotes"),
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Text,
    placeholder: t("summary.placeholders.addNote"),
  },
  {
    isEditable: true,
    key: SummaryFieldKey.RiskSuicidalThoughts,
    label: t("summary.fields.riskSuicidalThoughts"),
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Dropdown,
    options: ["Yes", "No"],
    placeholder: t("summary.placeholders.select"),
  },
  {
    isEditable: true,
    key: SummaryFieldKey.RiskSuicidalThoughtsNotes,
    label: t("summary.fields.riskSuicidalThoughtsNotes"),
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Text,
    placeholder: t("summary.placeholders.addNote"),
  },
  {
    isEditable: true,
    key: SummaryFieldKey.RiskSuicidalPlan,
    label: t("summary.fields.riskSuicidalPlan"),
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Dropdown,
    options: ["Yes", "No"],
    placeholder: t("summary.placeholders.select"),
  },
  {
    isEditable: true,
    key: SummaryFieldKey.RiskSuicidalAction,
    label: t("summary.fields.riskSuicidalAction"),
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Dropdown,
    options: ["Yes", "No"],
    placeholder: t("summary.placeholders.select"),
  },
  {
    isEditable: true,
    key: SummaryFieldKey.RiskRunningAway,
    label: t("summary.fields.riskRunningAway"),
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Dropdown,
    options: ["Yes", "No"],
    placeholder: t("summary.placeholders.select"),
  },
  {
    isEditable: true,
    key: SummaryFieldKey.RiskRunningAwayNotes,
    label: t("summary.fields.riskRunningAwayNotes"),
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Text,
    placeholder: t("summary.placeholders.addNote"),
  },
  {
    isEditable: true,
    key: SummaryFieldKey.TraumaPhysicalAbuse,
    label: t("summary.fields.traumaPhysicalAbuse"),
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Dropdown,
    options: ["Yes", "No"],
    placeholder: t("summary.placeholders.select"),
  },
  {
    isEditable: true,
    key: SummaryFieldKey.TraumaSexualAbuse,
    label: t("summary.fields.traumaSexualAbuse"),
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Dropdown,
    options: ["Yes", "No"],
    placeholder: t("summary.placeholders.select"),
  },
  {
    isEditable: true,
    key: SummaryFieldKey.TraumaVerbalAbuse,
    label: t("summary.fields.traumaVerbalAbuse"),
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Dropdown,
    options: ["Yes", "No"],
    placeholder: t("summary.placeholders.select"),
  },
  {
    isEditable: true,
    key: SummaryFieldKey.TraumaNeglect,
    label: t("summary.fields.traumaNeglect"),
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Dropdown,
    options: ["Yes", "No"],
    placeholder: t("summary.placeholders.select"),
  },
  {
    isEditable: true,
    key: SummaryFieldKey.TraumaSeparationFromCaregiverParent,
    label: t("summary.fields.traumaSeparation"),
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Dropdown,
    options: ["Yes", "No"],
    placeholder: t("summary.placeholders.select"),
  },
  {
    isEditable: true,
    key: SummaryFieldKey.TraumaWitnessedDomesticViolence,
    label: t("summary.fields.traumaDomesticViolence"),
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Dropdown,
    options: ["Yes", "No"],
    placeholder: t("summary.placeholders.select"),
  },
  {
    isEditable: true,
    key: SummaryFieldKey.TraumaNotes,
    label: t("summary.fields.traumaNotes"),
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Text,
    placeholder: t("summary.placeholders.addNote"),
  },
  {
    isEditable: true,
    key: SummaryFieldKey.AssessmentPsychologicalDiagnosis,
    label: t("summary.fields.assessmentPsychDiagnosis"),
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Dropdown,
    options: ["Yes", "No"],
    placeholder: t("summary.placeholders.select"),
  },
  {
    isEditable: true,
    key: SummaryFieldKey.AssessmentPsychologicalDiagnosisNotes,
    label: t("summary.fields.assessmentPsychDiagnosisNotes"),
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Text,
    placeholder: t("summary.placeholders.addNote"),
  },
  {
    isEditable: true,
    key: SummaryFieldKey.AssessmentUseOfPsychotropicMedications,
    label: t("summary.fields.assessmentPsychotropicMeds"),
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Dropdown,
    options: ["Yes", "No"],
    placeholder: t("summary.placeholders.select"),
  },
  {
    isEditable: true,
    key: SummaryFieldKey.AssessmentUseOfPsychotropicMedicationsNotes,
    label: t("summary.fields.assessmentPsychotropicMedsNotes"),
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Text,
    placeholder: t("summary.placeholders.addNote"),
  },
  {
    isEditable: true,
    key: SummaryFieldKey.AssessmentHallucinations,
    label: t("summary.fields.assessmentHallucinations"),
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Dropdown,
    options: ["Yes", "No"],
    placeholder: t("summary.placeholders.select"),
  },
  {
    isEditable: true,
    key: SummaryFieldKey.AssessmentHallucinationsNotes,
    label: t("summary.fields.assessmentHallucinationsNotes"),
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Text,
    placeholder: t("summary.placeholders.addNote"),
  },
  {
    isEditable: true,
    key: SummaryFieldKey.AssessmentAffect,
    label: t("summary.fields.assessmentAffect"),
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Dropdown,
    options: ["Congruent", "Incongruent", "Flat", "Blunted"],
    placeholder: t("summary.placeholders.select"),
  },
  {
    isEditable: true,
    key: SummaryFieldKey.AssessmentSpeech,
    label: t("summary.fields.assessmentSpeech"),
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Dropdown,
    options: ["Clear & Coherent", "Sluttering", "Fast", "Slow", "Difficult to Understand"],
    placeholder: t("summary.placeholders.select"),
  },
  // Ongoing Risks
  {
    isEditable: true,
    key: SummaryFieldKey.OngoingRiskSelfHarm,
    label: t("summary.fields.ongoingRiskSelfHarm"),
    sectionKey: SummarySectionKey.OngoingRisks,
    type: FieldType.Dropdown,
    options: ["Yes", "No"],
    placeholder: t("summary.placeholders.select"),
  },
  {
    isEditable: true,
    key: SummaryFieldKey.OngoingRiskSelfHarmNotes,
    label: t("summary.fields.ongoingRiskSelfHarmNotes"),
    sectionKey: SummarySectionKey.OngoingRisks,
    type: FieldType.Text,
    placeholder: t("summary.placeholders.addNote"),
  },
  {
    isEditable: true,
    key: SummaryFieldKey.OngoingRiskSuicidalThoughts,
    label: t("summary.fields.ongoingRiskSuicidalThoughts"),
    sectionKey: SummarySectionKey.OngoingRisks,
    type: FieldType.Dropdown,
    options: ["Yes", "No"],
    placeholder: t("summary.placeholders.select"),
  },
  {
    isEditable: true,
    key: SummaryFieldKey.OngoingRiskSuicidalPlan,
    label: t("summary.fields.ongoingRiskSuicidalPlan"),
    sectionKey: SummarySectionKey.OngoingRisks,
    type: FieldType.Dropdown,
    options: ["Yes", "No"],
    placeholder: t("summary.placeholders.select"),
  },
  {
    isEditable: true,
    key: SummaryFieldKey.OngoingRiskSuicidalAction,
    label: t("summary.fields.ongoingRiskSuicidalAction"),
    sectionKey: SummarySectionKey.OngoingRisks,
    type: FieldType.Dropdown,
    options: ["Yes", "No"],
    placeholder: t("summary.placeholders.select"),
  },
  {
    isEditable: true,
    key: SummaryFieldKey.OngoingRiskSuicidalThoughtsNotes,
    label: t("summary.fields.ongoingRiskSuicidalThoughtsNotes"),
    sectionKey: SummarySectionKey.OngoingRisks,
    type: FieldType.Text,
    placeholder: t("summary.placeholders.addNote"),
  },
];

// ─── Static fallbacks (used by utils.ts and other non-component files) ────────

export const summaryTabs = [
  { label: "Return to Self", value: SectionType.BoxBreathing },
  { label: "Session summary", value: SectionType.SessionSummary },
];

export const summarySections = [
  {
    icon: { icon: CallDetails, alt: "features-and-demographics" },
    key: SummarySectionKey.FeaturesAndDemographics,
    title: "Features and Demographics",
  },
  {
    icon: { icon: SessionSummary, alt: "session-summary" },
    key: SummarySectionKey.SessionSummary,
    title: "Session Summary",
  },
  { icon: { icon: Flow, alt: "flow" }, key: SummarySectionKey.Flow, title: "Flow" },
  {
    icon: { icon: KeyConcerns, alt: "key-concerns" },
    key: SummarySectionKey.KeyConcerns,
    title: "Key concerns",
  },
  {
    icon: { icon: ObjectiveObservations, alt: "objective-observations" },
    key: SummarySectionKey.ObjectiveObservations,
    title: "Objective Observations",
  },
  {
    icon: { icon: SubjectiveObservations, alt: "subjective-observations" },
    key: SummarySectionKey.SubjectiveObservations,
    title: "Subjective Observations",
  },
  {
    icon: { icon: Assessment, alt: "assessment" },
    key: SummarySectionKey.Assessment,
    title: "Assessment",
  },
  {
    icon: { icon: DominantFeelings, alt: "dominant-feelings" },
    key: SummarySectionKey.DominantFeelings,
    title: "Dominant Feelings",
  },
  {
    icon: { icon: IssuesWorkedOn, alt: "issues-worked-on" },
    key: SummarySectionKey.IssuesWorkedOn,
    title: "Issues Worked On",
  },
  {
    icon: { icon: TherapeuticTechniques, alt: "key-therapeutic-techniques" },
    key: SummarySectionKey.KeyTherapeuticTechniques,
    title: "Key Therapeutic Techniques",
  },
  {
    icon: { icon: ReferralsProvided, alt: "referrals-provided" },
    key: SummarySectionKey.ReferralsProvided,
    title: "Referrals Provided",
  },
  {
    icon: { icon: HomeworkRecommended, alt: "homework-recommended" },
    key: SummarySectionKey.HomeworkRecommended,
    title: "Homework Recommended",
  },
  {
    icon: { icon: PlansForNextCall, alt: "plans-for-next-call" },
    key: SummarySectionKey.PlansForNextCall,
    title: "Plans for Next Call",
  },
  { icon: { icon: Tags, alt: "tags" }, key: SummarySectionKey.Tags, title: "Tags" },
  { icon: { icon: Metrics, alt: "metrics" }, key: SummarySectionKey.Metrics, title: "Metrics" },
  { icon: { icon: Intake, alt: "intake" }, key: SummarySectionKey.Intake, title: "Intake" },
  {
    icon: { icon: OngoingRisks, alt: "ongoing-risks" },
    key: SummarySectionKey.OngoingRisks,
    title: "Ongoing Risks",
  },
];

export const summaryFields: SummaryField[] = [
  {
    isEditable: false,
    key: SummaryFieldKey.CallId,
    label: "Call ID",
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Text,
  },
  {
    isEditable: false,
    key: SummaryFieldKey.CallDuration,
    label: "Call Duration",
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Text,
  },
  {
    isEditable: false,
    key: SummaryFieldKey.CallDate,
    label: "Call Date",
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Text,
  },
  {
    isEditable: false,
    key: SummaryFieldKey.CallTime,
    label: "Call time",
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Text,
  },
  {
    isEditable: true,
    key: SummaryFieldKey.NewCallFollowUp,
    label: "New Call Follow Up",
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Text,
  },
  {
    isEditable: true,
    key: SummaryFieldKey.Counsellor,
    label: "Counsellor",
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Text,
  },
  {
    isEditable: true,
    key: SummaryFieldKey.CallQuality,
    label: "Call Quality",
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Text,
  },
  {
    isEditable: false,
    key: SummaryFieldKey.ClientId,
    label: "Caller ID",
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Text,
  },
  {
    isEditable: false,
    key: SummaryFieldKey.CounsellorName,
    label: "User Name",
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Text,
  },
  {
    isEditable: false,
    key: SummaryFieldKey.CallType,
    label: "Caller type",
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Text,
  },
  {
    isEditable: true,
    key: SummaryFieldKey.Age,
    label: "Age",
    options: ["0-5", "6-12", "13-17", "18-24", "25-34", "35-44", "45-54", "55-64", "65+"],
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Dropdown,
  },
  {
    isEditable: true,
    key: SummaryFieldKey.Gender,
    label: "Gender",
    options: ["Male", "Female", "Non-binary", "Client Prefers Not to Say"],
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Dropdown,
  },
  {
    isEditable: true,
    key: SummaryFieldKey.Profession,
    label: "Profession",
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Text,
  },
  {
    isEditable: true,
    key: SummaryFieldKey.RelationshipStatus,
    label: "Relationship status",
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Text,
  },
  {
    isEditable: false,
    key: SummaryFieldKey.Languages,
    label: "Languages",
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Text,
  },
  {
    isEditable: true,
    key: SummaryFieldKey.Location,
    label: "Location",
    options: [],
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Dropdown,
  },
  {
    isEditable: true,
    key: SummaryFieldKey.CodeOfConcern,
    label: "Concern code",
    sectionKey: SummarySectionKey.FeaturesAndDemographics,
    type: FieldType.Text,
  },
  {
    isEditable: true,
    isEnhanceable: true,
    key: SummaryFieldKey.SessionSummary,
    label: "Session Summary",
    placeholder: "Add a short summary of the session’s main points here.",
    sectionKey: SummarySectionKey.SessionSummary,
    type: FieldType.Multiline,
  },
  {
    isEditable: true,
    isEnhanceable: true,
    key: SummaryFieldKey.CounselingProcessFlow,
    label: "Flow",
    placeholder:
      "Capture the flow of conversation, reflections, or shifts in the client's mood here.",
    sectionKey: SummarySectionKey.Flow,
    type: FieldType.Multiline,
  },
  {
    isEditable: true,
    isEnhanceable: true,
    key: SummaryFieldKey.KeyConcerns,
    label: "Key concerns",
    placeholder: "List any main concerns or stressors raised by the client in this session.",
    sectionKey: SummarySectionKey.KeyConcerns,
    type: FieldType.Multiline,
  },
  {
    isEditable: true,
    isEnhanceable: true,
    key: SummaryFieldKey.ObjectiveObservations,
    label: "Objective Observations",
    placeholder: "Note factual observations or statements made by the client here.",
    sectionKey: SummarySectionKey.ObjectiveObservations,
    type: FieldType.Multiline,
  },
  {
    isEditable: true,
    isEnhanceable: true,
    key: SummaryFieldKey.SubjectiveObservations,
    label: "Subjective Observations",
    placeholder: "Use this space for your impressions, intuitions, or emotional insights.",
    sectionKey: SummarySectionKey.SubjectiveObservations,
    type: FieldType.Multiline,
  },
  {
    isEditable: true,
    isEnhanceable: true,
    key: SummaryFieldKey.Assessment,
    label: "Assessment",
    placeholder: "Summarize your take or therapeutic impression from today's session",
    sectionKey: SummarySectionKey.Assessment,
    type: FieldType.Multiline,
  },
  {
    isEditable: true,
    isEnhanceable: true,
    key: SummaryFieldKey.DominantFeelings,
    label: "Dominant Feelings",
    placeholder: "Highlight any emotions that stood out strongly during the session.",
    sectionKey: SummarySectionKey.DominantFeelings,
    type: FieldType.Multiline,
  },
  {
    isEditable: true,
    isEnhanceable: true,
    key: SummaryFieldKey.IssuesWorkedOn,
    label: "Issues Worked On",
    placeholder: "Mention what was explored or worked on during the session.",
    sectionKey: SummarySectionKey.IssuesWorkedOn,
    type: FieldType.Multiline,
  },
  {
    isEditable: true,
    isEnhanceable: true,
    key: SummaryFieldKey.KeyTherapeuticTechniques,
    label: "Key Therapeutic Techniques",
    placeholder: "Note any tools, frameworks, or strategies applied in the session.",
    sectionKey: SummarySectionKey.KeyTherapeuticTechniques,
    type: FieldType.Multiline,
  },
  {
    isEditable: true,
    isEnhanceable: true,
    key: SummaryFieldKey.ReferralsProvided,
    label: "Referrals Provided",
    placeholder: "Note any internal or external referrals or resources shared with the client.",
    sectionKey: SummarySectionKey.ReferralsProvided,
    type: FieldType.Multiline,
  },
  {
    isEditable: true,
    isEnhanceable: true,
    key: SummaryFieldKey.Homework,
    label: "Homework Recommended",
    placeholder: "Add suggestions or tasks for the client to work on between sessions.",
    sectionKey: SummarySectionKey.HomeworkRecommended,
    type: FieldType.Multiline,
  },
  {
    isEditable: true,
    isEnhanceable: true,
    key: SummaryFieldKey.PlanForNextCall,
    label: "Plans for Next Call",
    placeholder: "Mention goals or topics to revisit in the next session.",
    sectionKey: SummarySectionKey.PlansForNextCall,
    type: FieldType.Multiline,
  },
  {
    isEditable: true,
    isEnhanceable: false,
    key: SummaryFieldKey.Tags,
    label: "Tags",
    placeholder: "Add keywords to help organize or categorize this session.",
    sectionKey: SummarySectionKey.Tags,
    type: FieldType.Multiline,
  },
  {
    isEditable: false,
    key: SummaryFieldKey.ListeningShare,
    label: "Listening Ratio",
    sectionKey: SummarySectionKey.Metrics,
    type: FieldType.Text,
  },
  {
    isEditable: false,
    key: SummaryFieldKey.ReflectiveQuestionsAsked,
    label: "No of Reflective Questions asked",
    sectionKey: SummarySectionKey.Metrics,
    type: FieldType.Text,
  },
  {
    isEditable: false,
    key: SummaryFieldKey.EmotionalLift,
    label: "Emotions Lift",
    sectionKey: SummarySectionKey.Metrics,
    type: FieldType.Text,
  },
  {
    isEditable: false,
    key: SummaryFieldKey.OpenEndedQuestionsAsked,
    label: "No of Open Ended Questions asked",
    sectionKey: SummarySectionKey.Metrics,
    type: FieldType.Text,
  },
  {
    isEditable: true,
    key: SummaryFieldKey.IntakeNotes,
    label: "Intake Notes",
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Text,
    placeholder: "Add note",
  },
  {
    isEditable: true,
    key: SummaryFieldKey.RiskSelfHarm,
    label: "Risk, Self Harm",
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Dropdown,
    options: ["Yes", "No"],
    placeholder: "Select",
  },
  {
    isEditable: true,
    key: SummaryFieldKey.RiskSelfHarmNotes,
    label: "Risk, Self Harm Notes",
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Text,
    placeholder: "Add note",
  },
  {
    isEditable: true,
    key: SummaryFieldKey.RiskSuicidalThoughts,
    label: "Risk, Suicidal Thoughts",
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Dropdown,
    options: ["Yes", "No"],
    placeholder: "Select",
  },
  {
    isEditable: true,
    key: SummaryFieldKey.RiskSuicidalThoughtsNotes,
    label: "Risk, Suicidal Thoughts Notes",
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Text,
    placeholder: "Add note",
  },
  {
    isEditable: true,
    key: SummaryFieldKey.RiskSuicidalPlan,
    label: "Risk, Suicidal Plan",
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Dropdown,
    options: ["Yes", "No"],
    placeholder: "Select",
  },
  {
    isEditable: true,
    key: SummaryFieldKey.RiskSuicidalAction,
    label: "Risk, Suicidal Action",
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Dropdown,
    options: ["Yes", "No"],
    placeholder: "Select",
  },
  {
    isEditable: true,
    key: SummaryFieldKey.RiskRunningAway,
    label: "Risk, Running Away",
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Dropdown,
    options: ["Yes", "No"],
    placeholder: "Select",
  },
  {
    isEditable: true,
    key: SummaryFieldKey.RiskRunningAwayNotes,
    label: "Risk, Running Away Notes",
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Text,
    placeholder: "Add note",
  },
  {
    isEditable: true,
    key: SummaryFieldKey.TraumaPhysicalAbuse,
    label: "Trauma, Physical Abuse",
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Dropdown,
    options: ["Yes", "No"],
    placeholder: "Select",
  },
  {
    isEditable: true,
    key: SummaryFieldKey.TraumaSexualAbuse,
    label: "Trauma, Sexual Abuse",
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Dropdown,
    options: ["Yes", "No"],
    placeholder: "Select",
  },
  {
    isEditable: true,
    key: SummaryFieldKey.TraumaVerbalAbuse,
    label: "Trauma, Verbal Abuse",
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Dropdown,
    options: ["Yes", "No"],
    placeholder: "Select",
  },
  {
    isEditable: true,
    key: SummaryFieldKey.TraumaNeglect,
    label: "Trauma, Neglect",
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Dropdown,
    options: ["Yes", "No"],
    placeholder: "Select",
  },
  {
    isEditable: true,
    key: SummaryFieldKey.TraumaSeparationFromCaregiverParent,
    label: "Trauma, Separation from Caregiver/Parent",
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Dropdown,
    options: ["Yes", "No"],
    placeholder: "Select",
  },
  {
    isEditable: true,
    key: SummaryFieldKey.TraumaWitnessedDomesticViolence,
    label: "Trauma, Witnessed Domestic Violence",
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Dropdown,
    options: ["Yes", "No"],
    placeholder: "Select",
  },
  {
    isEditable: true,
    key: SummaryFieldKey.TraumaNotes,
    label: "Trauma Notes",
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Text,
    placeholder: "Add note",
  },
  {
    isEditable: true,
    key: SummaryFieldKey.AssessmentPsychologicalDiagnosis,
    label: "Assessment, Psychological Diagnosis",
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Dropdown,
    options: ["Yes", "No"],
    placeholder: "Select",
  },
  {
    isEditable: true,
    key: SummaryFieldKey.AssessmentPsychologicalDiagnosisNotes,
    label: "Assessment, Psychological Diagnosis Notes",
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Text,
    placeholder: "Add note",
  },
  {
    isEditable: true,
    key: SummaryFieldKey.AssessmentUseOfPsychotropicMedications,
    label: "Assessment, Use of Psychotropic Medications",
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Dropdown,
    options: ["Yes", "No"],
    placeholder: "Select",
  },
  {
    isEditable: true,
    key: SummaryFieldKey.AssessmentUseOfPsychotropicMedicationsNotes,
    label: "Assessment, Use of Psychotropic Medications Notes",
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Text,
    placeholder: "Add note",
  },
  {
    isEditable: true,
    key: SummaryFieldKey.AssessmentHallucinations,
    label: "Assessment, Hallucinations",
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Dropdown,
    options: ["Yes", "No"],
    placeholder: "Select",
  },
  {
    isEditable: true,
    key: SummaryFieldKey.AssessmentHallucinationsNotes,
    label: "Assessment, Hallucinations Notes",
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Text,
    placeholder: "Add note",
  },
  {
    isEditable: true,
    key: SummaryFieldKey.AssessmentAffect,
    label: "Assessment, Affect",
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Dropdown,
    options: ["Congruent", "Incongruent", "Flat", "Blunted"],
    placeholder: "Select",
  },
  {
    isEditable: true,
    key: SummaryFieldKey.AssessmentSpeech,
    label: "Assessment, Speech",
    sectionKey: SummarySectionKey.Intake,
    type: FieldType.Dropdown,
    options: ["Clear & Coherent", "Sluttering", "Fast", "Slow", "Difficult to Understand"],
    placeholder: "Select",
  },
  {
    isEditable: true,
    key: SummaryFieldKey.OngoingRiskSelfHarm,
    label: "Ongoing Risk, Self Harm",
    sectionKey: SummarySectionKey.OngoingRisks,
    type: FieldType.Dropdown,
    options: ["Yes", "No"],
    placeholder: "Select",
  },
  {
    isEditable: true,
    key: SummaryFieldKey.OngoingRiskSelfHarmNotes,
    label: "Ongoing Risk, Self Harm Notes",
    sectionKey: SummarySectionKey.OngoingRisks,
    type: FieldType.Text,
    placeholder: "Add note",
  },
  {
    isEditable: true,
    key: SummaryFieldKey.OngoingRiskSuicidalThoughts,
    label: "Ongoing Risk, Suicidal Thoughts",
    sectionKey: SummarySectionKey.OngoingRisks,
    type: FieldType.Dropdown,
    options: ["Yes", "No"],
    placeholder: "Select",
  },
  {
    isEditable: true,
    key: SummaryFieldKey.OngoingRiskSuicidalPlan,
    label: "Ongoing Risk, Suicidal Plan",
    sectionKey: SummarySectionKey.OngoingRisks,
    type: FieldType.Dropdown,
    options: ["Yes", "No"],
    placeholder: "Select",
  },
  {
    isEditable: true,
    key: SummaryFieldKey.OngoingRiskSuicidalAction,
    label: "Ongoing Risk, Suicidal Action",
    sectionKey: SummarySectionKey.OngoingRisks,
    type: FieldType.Dropdown,
    options: ["Yes", "No"],
    placeholder: "Select",
  },
  {
    isEditable: true,
    key: SummaryFieldKey.OngoingRiskSuicidalThoughtsNotes,
    label: "Ongoing Risk, Suicidal Thoughts Notes",
    sectionKey: SummarySectionKey.OngoingRisks,
    type: FieldType.Text,
    placeholder: "Add note",
  },
];

export const labelShownSections = [
  SummarySectionKey.FeaturesAndDemographics,
  SummarySectionKey.Metrics,
];

export const postCallSectionOrder = [SectionType.BoxBreathing, SectionType.SessionSummary];

export const SectionQueryKey = "section";

export const SourceQueryKey = "source";

export const DeeplinkSourceValue = "deeplink";

export const getPostCallProcessingMessages = (t: TFunction) => [
  t("summaryLoading.processing.generatingTranscription"),
  t("summaryLoading.processing.deletingAudio"),
  t("summaryLoading.processing.segregatingUtterances"),
  t("summaryLoading.processing.understandingConversation"),
  t("summaryLoading.processing.chartingFlow"),
  t("summaryLoading.processing.extractingKeyPoints"),
  t("summaryLoading.processing.identifyingThemes"),
  t("summaryLoading.processing.analysing"),
  t("summaryLoading.processing.generatingSummary"),
  t("summaryLoading.processing.enrichingSummary"),
  t("summaryLoading.processing.validatingSummary"),
];

export const PostCallProcessingMessages = [
  "Generating transcription",
  "Deleting audio",
  "Segregating utterances",
  "Understanding conversation",
  "Charting flow",
  "Extracting key points",
  "Identifying themes",
  "Analysing",
  "Generating summary",
  "Enriching summary",
  "Validating summary",
];

// TODO: Decide on a format for const files
// Start index of summary message that should be looped
export const SUMMARY_GENERATION_START_INDEX = 8;
