/** Wire types for the Product Roadmap board. Mirrors ally-be src/product-roadmap DTOs. */

export enum RoadmapOpportunityType {
  IDEA = "idea",
  BUG = "bug",
}

/**
 * Rough size of the work, on the shirt-size scale teams already use.
 *
 * Coarse ON PURPOSE: the roadmap decides what is next, which needs "a week or a quarter", not
 * "13 points or 21" on something nobody has broken down. Values mirror ally-be's
 * RoadmapOpportunityEffort and are the wire format — lowercase on the wire, shirt sizes on
 * screen (see EFFORT_LABEL).
 */
export enum RoadmapOpportunityEffort {
  S = "s",
  M = "m",
  L = "l",
  XL = "xl",
  XXL = "xxl",
}

export enum RoadmapOpportunityStage {
  NEW = "new",
  PRIORITISED = "prioritised",
  UNDER_DEVELOPMENT = "under_development",
  RELEASED = "released",
  ARCHIVED = "archived",
}

/**
 * Who filed it — 'staff' (somebody internal, and every pre-existing row) or 'consumer' (an
 * app user). Answers "who", not "through which client": a bug report is stamped from the
 * reporter's own roles server-side, so an admin filing from helpline still reads as staff.
 * Admin-side display/filtering only, mirrors ally-be's RoadmapOpportunitySource.
 */
export enum RoadmapOpportunitySource {
  STAFF = "staff",
  CONSUMER = "consumer",
}

/**
 * Silently-captured triage context sent alongside a bug report. The reporter types one
 * sentence and never sees any of this — it is shown to a triager in Bug Hunter's drawer as
 * evidence beside their words. Every field is optional server-side, so a miss degrades the
 * report rather than failing it. Mirrors ally-be's ReporterContextDto.
 */
export interface RoadmapBugReportContext {
  screen?: string;
  appVersion?: string;
  device?: string;
  os?: string;
  clientTimestamp?: string;
}

export interface RoadmapBugReportBody {
  description: string;
  context?: RoadmapBugReportContext;
}

/** One-time confirmation: there is deliberately no "my reports" list to link back to. */
export interface RoadmapBugReportResponse {
  id: string;
  stage: string;
}

export interface RoadmapUserRef {
  id: number;
  email: string;
  /** "Unknown user" when the Ally account no longer exists — createdBy has no FK. */
  name: string;
}

export interface RoadmapOpportunity {
  id: string;
  description: string;
  type: RoadmapOpportunityType;
  stage: RoadmapOpportunityStage;
  productGoal: string;
  /** Display name: the linked super-admin's current name, or a legacy migrated string. */
  owner: string | null;
  /** Null for legacy migrated rows whose owner was never linked to an Ally account. */
  ownerUserId?: number | null;
  prd: string | null;
  /** AI-generated Claude Code implementation prompt, saved verbatim like `prd`. */
  /**
   * Short human-quotable id, e.g. 'OPP-0042'. Unique and never reused, generated by a column
   * default in ally-be — the client never sets it.
   */
  code: string;
  /**
   * Position in the queue (New / Prioritised / In development) by total votes — 1-based, unique,
   * and null outside those stages. Computed by ally-be per read, so it always reflects current
   * stages and vote totals and does NOT change when the caller filters or searches.
   */
  queueRank: number | null;
  claudePrompt: string | null;
  /**
   * The Builder session started from this opportunity, or null.
   *
   * Present on the detail response only in practice, but typed here because the board rows and
   * the drawer share this shape — a row simply never renders it.
   */
  builderSessionId: string | null;
  releasedAt: string | null;
  /** The month this was PLANNED into, 'YYYY-MM'. Null means Unscheduled. */
  plannedMonth: string | null;
  /**
   * Rough size of the work. Null means nobody has sized it — a real and permanent state, not a
   * gap: every row predating the field is unsized and no backfill can honestly invent one.
   */
  effort: RoadmapOpportunityEffort | null;
  /** Manual rank within its month lane, ascending. Only meaningful against its own lane. */
  boardPosition: number;
  /**
   * The lane the card actually shows in: its release month once shipped, else plannedMonth.
   * Server-derived — never recompute it here, or the board and the API will disagree about
   * where a slipped item lives.
   */
  effectiveMonth: string | null;
  /** True when the lane is a fact rather than a plan, so the card must not be draggable. */
  monthPinned: boolean;
  /** SUM of every user's votes across every period. Computed in SQL, never stored. */
  priorityScore: number;
  /** The CALLER's votes on this opportunity in the CURRENT period only. */
  myVotes: number;
  commentCount: number;
  /** Who filed it — see RoadmapOpportunitySource. Admin display only. */
  source: RoadmapOpportunitySource;
  createdAt: string;
  updatedAt: string;
  creator: RoadmapUserRef | null;
}

export interface RoadmapOpportunitiesResponse {
  items: RoadmapOpportunity[];
  count: number;
  /**
   * MAX score across ALL non-deleted opportunities — deliberately unfiltered, so the priority
   * bars keep a stable scale when a filter is applied.
   */
  maxScore: number;
  /** Server-computed 'YYYY-MM'. Never derive this on the client. */
  periodKey: string;
}

export interface RoadmapOpportunitiesQuery {
  search?: string;
  type?: string[];
  stage?: string[];
  source?: string[];
  productGoal?: string[];
  owner?: string[];
  createdBy?: number[];
  dateFrom?: string;
  dateTo?: string;
  releasedFrom?: string;
  releasedTo?: string;
  priorityMin?: number;
  priorityMax?: number;
  sortBy?: "priority" | "createdAt" | "releasedAt" | "myVotes" | "description" | "plannedMonth";
  order?: "ASC" | "DESC";
  limit?: number;
  offset?: number;
}

/**
 * Which layout the Opportunities tab is showing. Persisted in saved-view state.
 *
 * The value is still "month-board" although the layout is now just "Board" with a grouping
 * picker: it is written into every saved view, and renaming it would open every migrated view
 * on the table instead of the board it was saved on. RoadmapBoardGroupBy carries what used to
 * be implied by the name.
 */
export enum RoadmapBoardLayout {
  TABLE = "table",
  BOARD = "month-board",
  /** Single-column card feed — same query, sort and pagination as the table, no drag or merge-select. */
  LIST = "list",
}

/** What the board's lanes are. Mirrors RoadmapBoardGroupBy in ally-be. */
export enum RoadmapBoardGroupBy {
  MONTH = "month",
  STAGE = "stage",
  PRODUCT_GOAL = "productGoal",
  OWNER = "owner",
}

export interface RoadmapBoardLane {
  /**
   * The lane's value: 'YYYY-MM' when grouping by month, the stage / goal / owner otherwise.
   * Null is the catch-all lane — Unscheduled, No goal, No owner — which the stage board has
   * none of, because stage is NOT NULL.
   */
  key: string | null;
  items: RoadmapOpportunity[];
  /** True lane size, which is NOT items.length when laneLimit truncated it. */
  total: number;
}

export interface RoadmapBoardResponse {
  groupBy: RoadmapBoardGroupBy;
  /**
   * Every lane in display order, INCLUDING empty ones — a gap in a plan is information, and so
   * is a product goal nobody is working on. The catch-all lane is FIRST for month (Unscheduled
   * has always been leftmost) and LAST for the others, where it is a residue.
   */
  lanes: RoadmapBoardLane[];
  /** Earliest/latest month holding anything at all. Unfiltered, so the window arrows don't flicker. */
  bounds: { earliest: string | null; latest: string | null };
  from: string;
  to: string;
  maxScore: number;
  periodKey: string;
  /** True when the board hit its global row bound and some lanes are incomplete. */
  truncated: boolean;
}

/** The board read. Same filters as the table, windowed by month instead of paginated. */
export type RoadmapBoardQuery = Omit<
  RoadmapOpportunitiesQuery,
  "sortBy" | "order" | "limit" | "offset"
> & {
  from?: string;
  to?: string;
  laneLimit?: number;
  /** Defaults to month server-side. `from`/`to` are ignored by the other groupings. */
  groupBy?: RoadmapBoardGroupBy;
};

export interface RoadmapBoardMoveResponse {
  opportunityId: string;
  plannedMonth: string | null;
  effectiveMonth: string | null;
  /** The ids actually rewritten — shorter than what was sent if the drag was stale. */
  reordered: string[];
}

export interface RoadmapVoteBudget {
  periodKey: string;
  votesPerMonth: number;
  used: number;
  remaining: number;
}

/**
 * Returned by PUT /allocations. Carries BOTH the opportunity aggregate and the budget so an
 * optimistic client reconciles in one round-trip instead of refetching the list (which would
 * stomp an in-flight vote edit).
 */
export interface SetAllocationResponse {
  opportunityId: string;
  periodKey: string;
  votes: number;
  priorityScore: number;
  budget: RoadmapVoteBudget;
}

export interface RoadmapFacets {
  creators: RoadmapUserRef[];
  goals: string[];
  owners: string[];
}

export interface RoadmapTaxonomyItem {
  id: string;
  name: string;
  position: number;
}

export interface RoadmapComment {
  id: string;
  opportunityId: string;
  body: string;
  createdBy: number;
  updatedBy: number;
  createdAt: string;
  updatedAt: string;
}

export interface RoadmapInterviewNote {
  id: string;
  title: string;
  interviewee: string | null;
  transcript: string | null;
  summary: string;
  createdBy: number;
  createdAt: string;
  updatedAt: string;
}

/**
 * A saved filter/sort snapshot.
 *
 * `goalFilter` and `ownerFilter` hold NAMES, not ids — which is why the backend keeps text
 * foreign keys with ON UPDATE CASCADE. Switching either side to uuids silently breaks every
 * migrated view.
 *
 * Key ORDER is not preserved by Postgres jsonb, so the dirty check must compare a canonically
 * key-ordered serialisation (see utils/views.ts). Comparing raw JSON.stringify output makes
 * every saved view look permanently dirty.
 */
export interface RoadmapViewState {
  searchQuery?: string;
  typeFilter?: string[];
  stageFilter?: string[];
  /** New filter, absent on every view saved before it existed — treat undefined as "no filter". */
  sourceFilter?: string[];
  goalFilter?: string[];
  ownerFilter?: string[];
  creatorFilter?: string[];
  dateFrom?: string;
  dateTo?: string;
  releasedFrom?: string;
  releasedTo?: string;
  priorityMin?: string;
  priorityMax?: string;
  sort?: { field: string; dir: "asc" | "desc" };
  /**
   * Which layout the view opens in. Absent on every view migrated from the standalone app and on
   * everything saved before month boards existed, which is why readers must default it to TABLE
   * rather than treat undefined as a distinct third state.
   */
  layout?: RoadmapBoardLayout;
}

export interface RoadmapSavedView {
  id: string;
  name: string;
  state: RoadmapViewState;
  pinned: boolean;
  createdBy: number;
  createdAt: string;
  updatedAt: string;
}

export interface RoadmapDuplicateMatch {
  id: string;
  description: string;
  productGoal: string;
  stage: RoadmapOpportunityStage;
  reason: string;
  similarity: number;
}

export interface RoadmapListEnvelope<T> {
  items: T[];
  count: number;
}

/** An Ally super-admin who may be assigned as an opportunity owner. */
export interface RoadmapEligibleOwner {
  id: number;
  name: string;
  email: string;
}

/**
 * What the roadmap gets back from opening a Builder session.
 *
 * `created` decides whether the drawer seeds the interview: a resumed session already opens with
 * the brief, and sending it again would put the same paragraph in the transcript twice.
 */
export interface RoadmapBuilderSessionHandle {
  sessionId: string;
  created: boolean;
  seedMessage: string | null;
}
