export const ApiEndpoints = {
  AUTH: {
    SIGNUP: "/auth/signup",
    LOGIN: "/auth/login",
    GET_USER: "/users/me",
    GENERATE_OTP: "/auth/generate-otp",
    VERIFY_OTP: "/auth/verify-otp",
    REFRESH: "/auth/refresh",
  },
  AUTHORIZATION: {
    GET_PERMISSIONS: "/authorization/permissions",
  },
  ANALYTICS: {
    GET_DASHBOARD: "/analytics/dashboard",
    GET_COUNSELLOR_STATS: "/analytics/counselor-stats",
  },
  AUDIO_CALL: {
    GET_WAITING_CLIENTS: "/users/waiting-list",
    REQUEST_CALL: "/chats/request",
    GET_CLIENT_CHAT: "/chats/my-chat",
    GET_COUNSELLOR_CHAT: "/chats/counsellor-chat",
    GET_NUDGE_STATUS: "/settings/nudge-status",
    // Template functions for dynamic endpoints
    CANCEL_CHAT: (chatId: number) => `/chats/${chatId}/cancel`,
    ACCEPT_CHAT: (chatId: number) => `/chats/${chatId}/accept`,
    END_CHAT: (chatId: number) => `/chats/${chatId}/end`,
    MESSAGE_FEEDBACK: (messageId: number) => `chats/messages/${messageId}/feedback`,
    UPDATE_FEEDBACK: (feedbackId: number) => `chats/messages/feedback/${feedbackId}`,
  },
  CALLS: {
    GET_CALL_LOGS: "/chats/call-logs",
    GET_ADMIN_CALL_LOGS: "/chats/call-logs-summary",
    GET_COUNSELLORS: "/chats/counselors",
    GET_CALL_TAGS: "/chats/tags",
    GET_CHAT_TYPES: "/settings/chat-types",
    GET_AUDIO_UPLOAD_URL: "/chats/upload-url",
    CANCEL_AUDIO_UPLOAD: "/chats/cancel-upload",
    DELETE_CALL_LOG: (chatId: number) => `/chats/${chatId}`,
  },
  CALL_SUMMARY: {
    GET_SUMMARY_FIELDS: "/settings/summary-fields",
    GET_CALL_SUMMARY: "/chats",
    ENHANCE_CONTENT: "/chats/enhance",
    GET_TAG_POSITIVITY_RATINGS: "/chats/summary/tag-positivity-ratings",
    GET_LOCATIONS: "/places",
    SEARCH_LOCATIONS: "/places/search",
    UPDATE_CALL_INFO: (chatId: number) => `/chats/${chatId}/call-info`,
    UPDATE_CALL_SUMMARY: (chatId: number) => `/chats/${chatId}/call-details`,
    EXPORT_CALL_SUMMARY: (chatId: number) => `/chats/${chatId}/export-summary`,
    GET_TRANSCRIPT: (chatId: number) => `/chats/${chatId}/messages`,
    UPDATE_CALL_SUMMARY_NOTES: (chatId: string) => `/chats/${chatId}/notes`,
    SUBMIT_FEEDBACK: (chatId: string) => `/chats/${chatId}/summary-feedback`,
  },
  SEARCH: {
    GET_CATEGORIES: "/reference-document/categories",
    GET_SEARCH_RESULTS: "/reference-document/search",
  },
  LEARN: {
    END_SIMULATION: (sessionId: string) => `/learn/scenario-session/${sessionId}/end`,
    START_SIMULATION: "/learn/scenario-session-start",
    GET_SCENARIOS: "/learn/scenarios",
    GET_SCENARIO: (scenarioId: number) => `/learn/scenarios/${scenarioId}`,
    GET_SIMULATION_LOGS: "/learn/scenario-sessions",
    GET_ADMIN_SIMULATION_LOGS: "/learn/admin-scenario-sessions",
    GET_SIMULATION_SUMMARY: (sessionId: string) => `/learn/scenario-session/${sessionId}`,
    SUBMIT_SIMULATION_FEEDBACK: (sessionId: string) =>
      `/learn/scenario-session/${sessionId}/feedback`,
    GET_SIMULATION_TRANSCRIPT: (sessionId: string) =>
      `/learn/scenario-session/${sessionId}/messages`,
  },
};
