export enum CallType {
  WEBRTC_CHAT = "WEBRTC_CHAT",
  MICROPHONE_CHAT = "MICROPHONE_CHAT",
  EXOTEL_CONFERENCE_CHAT = "EXOTEL_CONFERENCE_CHAT",
}

export enum CallProvider {
  WEBRTC = "WEBRTC",
  MICROPHONE = "MICROPHONE",
  EXOTEL_CONFERENCE_CALL = "EXOTEL_CONFERENCE_CALL",
}
