export enum TabId {
  CALLS = "CALLS",
  CALENDER = "CALENDER",
  LEARN = "LEARN",
  STRESS_BUSTERS = "STRESS BUSTERS",
  ANALYTICS = "ANALYTICS",
  COMMUNITY = "COMMUNITY",
  SETTINGS = "SETTINGS",
}
