export enum TabId {
  ANALYTICS = "ANALYTICS",
  CALENDER = "CALENDER",
  SCRIBE_LOGS = "SCRIBE_LOGS",
  ROLEPLAY_LOGS = "ROLEPLAY_LOGS",
  LEARN = "LEARN",
  SEARCH = "SEARCH",
  SETTINGS = "SETTINGS",
  STRESS_BUSTERS = "STRESS BUSTERS",
  LEADERBOARD = "LEADERBOARD",
  REVIEW = "REVIEW",
  BADGES = "BADGES",
  ORGANIZATION_SETTINGS = "ORGANIZATION_SETTINGS",
  // Not an in-app tab: opens the Ally Admin console in a new tab.
  ALLY_ADMIN = "ALLY_ADMIN",
}
